//////////////////////////////////////////////////////////////
// This file was auto-generated by ruby_native_bindings.zig //
//              Do not manually modify.                     //
//////////////////////////////////////////////////////////////

#include <ruby.h>
#include "tb_client.h"
#include "tb_helpers.h"

void tb_define_enums_and_bitmasks(VALUE module) {

  VALUE mOperation = rb_define_module_under(module, "Operation");
  rb_define_const(mOperation, "PULSE", INT2NUM(128));
  rb_define_const(mOperation, "GET_EVENTS", INT2NUM(137));
  rb_define_const(mOperation, "CREATE_ACCOUNTS", INT2NUM(138));
  rb_define_const(mOperation, "CREATE_TRANSFERS", INT2NUM(139));
  rb_define_const(mOperation, "LOOKUP_ACCOUNTS", INT2NUM(140));
  rb_define_const(mOperation, "LOOKUP_TRANSFERS", INT2NUM(141));
  rb_define_const(mOperation, "GET_ACCOUNT_TRANSFERS", INT2NUM(142));
  rb_define_const(mOperation, "GET_ACCOUNT_BALANCES", INT2NUM(143));
  rb_define_const(mOperation, "QUERY_ACCOUNTS", INT2NUM(144));
  rb_define_const(mOperation, "QUERY_TRANSFERS", INT2NUM(145));

  VALUE mPacketStatus = rb_define_module_under(module, "PacketStatus");
  rb_define_const(mPacketStatus, "OK", INT2NUM(0));
  rb_define_const(mPacketStatus, "TOO_MUCH_DATA", INT2NUM(1));
  rb_define_const(mPacketStatus, "CLIENT_EVICTED", INT2NUM(2));
  rb_define_const(mPacketStatus, "CLIENT_RELEASE_TOO_LOW", INT2NUM(3));
  rb_define_const(mPacketStatus, "CLIENT_RELEASE_TOO_HIGH", INT2NUM(4));
  rb_define_const(mPacketStatus, "CLIENT_SHUTDOWN", INT2NUM(5));
  rb_define_const(mPacketStatus, "INVALID_OPERATION", INT2NUM(6));
  rb_define_const(mPacketStatus, "INVALID_DATA_SIZE", INT2NUM(7));

  VALUE mInitStatus = rb_define_module_under(module, "InitStatus");
  rb_define_const(mInitStatus, "SUCCESS", INT2NUM(0));
  rb_define_const(mInitStatus, "UNEXPECTED", INT2NUM(1));
  rb_define_const(mInitStatus, "OUT_OF_MEMORY", INT2NUM(2));
  rb_define_const(mInitStatus, "ADDRESS_INVALID", INT2NUM(3));
  rb_define_const(mInitStatus, "ADDRESS_LIMIT_EXCEEDED", INT2NUM(4));
  rb_define_const(mInitStatus, "SYSTEM_RESOURCES", INT2NUM(5));
  rb_define_const(mInitStatus, "NETWORK_SUBSYSTEM", INT2NUM(6));

  VALUE mClientStatus = rb_define_module_under(module, "ClientStatus");
  rb_define_const(mClientStatus, "OK", INT2NUM(0));
  rb_define_const(mClientStatus, "INVALID", INT2NUM(1));

  VALUE mLogLevel = rb_define_module_under(module, "LogLevel");
  rb_define_const(mLogLevel, "ERR", INT2NUM(0));
  rb_define_const(mLogLevel, "WARN", INT2NUM(1));
  rb_define_const(mLogLevel, "INFO", INT2NUM(2));
  rb_define_const(mLogLevel, "DEBUG", INT2NUM(3));

  VALUE mRegisterLogCallbackStatus = rb_define_module_under(module, "RegisterLogCallbackStatus");
  rb_define_const(mRegisterLogCallbackStatus, "SUCCESS", INT2NUM(0));
  rb_define_const(mRegisterLogCallbackStatus, "ALREADY_REGISTERED", INT2NUM(1));
  rb_define_const(mRegisterLogCallbackStatus, "NOT_REGISTERED", INT2NUM(2));

  VALUE mAccountFlags = rb_define_module_under(module, "AccountFlags");
  rb_define_const(mAccountFlags, "LINKED", INT2NUM(1 << 0));
  rb_define_const(mAccountFlags, "DEBITS_MUST_NOT_EXCEED_CREDITS", INT2NUM(1 << 1));
  rb_define_const(mAccountFlags, "CREDITS_MUST_NOT_EXCEED_DEBITS", INT2NUM(1 << 2));
  rb_define_const(mAccountFlags, "HISTORY", INT2NUM(1 << 3));
  rb_define_const(mAccountFlags, "IMPORTED", INT2NUM(1 << 4));
  rb_define_const(mAccountFlags, "CLOSED", INT2NUM(1 << 5));

  VALUE mTransferFlags = rb_define_module_under(module, "TransferFlags");
  rb_define_const(mTransferFlags, "LINKED", INT2NUM(1 << 0));
  rb_define_const(mTransferFlags, "PENDING", INT2NUM(1 << 1));
  rb_define_const(mTransferFlags, "POST_PENDING_TRANSFER", INT2NUM(1 << 2));
  rb_define_const(mTransferFlags, "VOID_PENDING_TRANSFER", INT2NUM(1 << 3));
  rb_define_const(mTransferFlags, "BALANCING_DEBIT", INT2NUM(1 << 4));
  rb_define_const(mTransferFlags, "BALANCING_CREDIT", INT2NUM(1 << 5));
  rb_define_const(mTransferFlags, "CLOSING_DEBIT", INT2NUM(1 << 6));
  rb_define_const(mTransferFlags, "CLOSING_CREDIT", INT2NUM(1 << 7));
  rb_define_const(mTransferFlags, "IMPORTED", INT2NUM(1 << 8));

  VALUE mAccountFilterFlags = rb_define_module_under(module, "AccountFilterFlags");
  rb_define_const(mAccountFilterFlags, "DEBITS", INT2NUM(1 << 0));
  rb_define_const(mAccountFilterFlags, "CREDITS", INT2NUM(1 << 1));
  rb_define_const(mAccountFilterFlags, "REVERSED", INT2NUM(1 << 2));

  VALUE mQueryFilterFlags = rb_define_module_under(module, "QueryFilterFlags");
  rb_define_const(mQueryFilterFlags, "REVERSED", INT2NUM(1 << 0));

  VALUE mCreateAccountResult = rb_define_module_under(module, "CreateAccountResult");
  rb_define_const(mCreateAccountResult, "OK", INT2NUM(0));
  rb_define_const(mCreateAccountResult, "LINKED_EVENT_FAILED", INT2NUM(1));
  rb_define_const(mCreateAccountResult, "LINKED_EVENT_CHAIN_OPEN", INT2NUM(2));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_EXPECTED", INT2NUM(22));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_NOT_EXPECTED", INT2NUM(23));
  rb_define_const(mCreateAccountResult, "TIMESTAMP_MUST_BE_ZERO", INT2NUM(3));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE", INT2NUM(24));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE", INT2NUM(25));
  rb_define_const(mCreateAccountResult, "RESERVED_FIELD", INT2NUM(4));
  rb_define_const(mCreateAccountResult, "RESERVED_FLAG", INT2NUM(5));
  rb_define_const(mCreateAccountResult, "ID_MUST_NOT_BE_ZERO", INT2NUM(6));
  rb_define_const(mCreateAccountResult, "ID_MUST_NOT_BE_INT_MAX", INT2NUM(7));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_FLAGS", INT2NUM(15));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_128", INT2NUM(16));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_64", INT2NUM(17));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_32", INT2NUM(18));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_LEDGER", INT2NUM(19));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_CODE", INT2NUM(20));
  rb_define_const(mCreateAccountResult, "EXISTS", INT2NUM(21));
  rb_define_const(mCreateAccountResult, "FLAGS_ARE_MUTUALLY_EXCLUSIVE", INT2NUM(8));
  rb_define_const(mCreateAccountResult, "DEBITS_PENDING_MUST_BE_ZERO", INT2NUM(9));
  rb_define_const(mCreateAccountResult, "DEBITS_POSTED_MUST_BE_ZERO", INT2NUM(10));
  rb_define_const(mCreateAccountResult, "CREDITS_PENDING_MUST_BE_ZERO", INT2NUM(11));
  rb_define_const(mCreateAccountResult, "CREDITS_POSTED_MUST_BE_ZERO", INT2NUM(12));
  rb_define_const(mCreateAccountResult, "LEDGER_MUST_NOT_BE_ZERO", INT2NUM(13));
  rb_define_const(mCreateAccountResult, "CODE_MUST_NOT_BE_ZERO", INT2NUM(14));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS", INT2NUM(26));

  VALUE mCreateTransferResult = rb_define_module_under(module, "CreateTransferResult");
  rb_define_const(mCreateTransferResult, "OK", INT2NUM(0));
  rb_define_const(mCreateTransferResult, "LINKED_EVENT_FAILED", INT2NUM(1));
  rb_define_const(mCreateTransferResult, "LINKED_EVENT_CHAIN_OPEN", INT2NUM(2));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_EXPECTED", INT2NUM(56));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_NOT_EXPECTED", INT2NUM(57));
  rb_define_const(mCreateTransferResult, "TIMESTAMP_MUST_BE_ZERO", INT2NUM(3));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE", INT2NUM(58));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE", INT2NUM(59));
  rb_define_const(mCreateTransferResult, "RESERVED_FLAG", INT2NUM(4));
  rb_define_const(mCreateTransferResult, "ID_MUST_NOT_BE_ZERO", INT2NUM(5));
  rb_define_const(mCreateTransferResult, "ID_MUST_NOT_BE_INT_MAX", INT2NUM(6));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_FLAGS", INT2NUM(36));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_PENDING_ID", INT2NUM(40));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_TIMEOUT", INT2NUM(44));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_DEBIT_ACCOUNT_ID", INT2NUM(37));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_CREDIT_ACCOUNT_ID", INT2NUM(38));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_AMOUNT", INT2NUM(39));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_128", INT2NUM(41));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_64", INT2NUM(42));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_32", INT2NUM(43));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_LEDGER", INT2NUM(67));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_CODE", INT2NUM(45));
  rb_define_const(mCreateTransferResult, "EXISTS", INT2NUM(46));
  rb_define_const(mCreateTransferResult, "ID_ALREADY_FAILED", INT2NUM(68));
  rb_define_const(mCreateTransferResult, "FLAGS_ARE_MUTUALLY_EXCLUSIVE", INT2NUM(7));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ID_MUST_NOT_BE_ZERO", INT2NUM(8));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX", INT2NUM(9));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ID_MUST_NOT_BE_ZERO", INT2NUM(10));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX", INT2NUM(11));
  rb_define_const(mCreateTransferResult, "ACCOUNTS_MUST_BE_DIFFERENT", INT2NUM(12));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_BE_ZERO", INT2NUM(13));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_NOT_BE_ZERO", INT2NUM(14));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_NOT_BE_INT_MAX", INT2NUM(15));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_BE_DIFFERENT", INT2NUM(16));
  rb_define_const(mCreateTransferResult, "TIMEOUT_RESERVED_FOR_PENDING_TRANSFER", INT2NUM(17));
  rb_define_const(mCreateTransferResult, "CLOSING_TRANSFER_MUST_BE_PENDING", INT2NUM(64));
  rb_define_const(mCreateTransferResult, "LEDGER_MUST_NOT_BE_ZERO", INT2NUM(19));
  rb_define_const(mCreateTransferResult, "CODE_MUST_NOT_BE_ZERO", INT2NUM(20));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_NOT_FOUND", INT2NUM(21));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_NOT_FOUND", INT2NUM(22));
  rb_define_const(mCreateTransferResult, "ACCOUNTS_MUST_HAVE_THE_SAME_LEDGER", INT2NUM(23));
  rb_define_const(mCreateTransferResult, "TRANSFER_MUST_HAVE_THE_SAME_LEDGER_AS_ACCOUNTS", INT2NUM(24));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_NOT_FOUND", INT2NUM(25));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_NOT_PENDING", INT2NUM(26));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_DEBIT_ACCOUNT_ID", INT2NUM(27));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_CREDIT_ACCOUNT_ID", INT2NUM(28));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_LEDGER", INT2NUM(29));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_CODE", INT2NUM(30));
  rb_define_const(mCreateTransferResult, "EXCEEDS_PENDING_TRANSFER_AMOUNT", INT2NUM(31));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_AMOUNT", INT2NUM(32));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_ALREADY_POSTED", INT2NUM(33));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_ALREADY_VOIDED", INT2NUM(34));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_EXPIRED", INT2NUM(35));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS", INT2NUM(60));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_DEBIT_ACCOUNT", INT2NUM(61));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_CREDIT_ACCOUNT", INT2NUM(62));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMEOUT_MUST_BE_ZERO", INT2NUM(63));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ALREADY_CLOSED", INT2NUM(65));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ALREADY_CLOSED", INT2NUM(66));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS_PENDING", INT2NUM(47));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS_PENDING", INT2NUM(48));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS_POSTED", INT2NUM(49));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS_POSTED", INT2NUM(50));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS", INT2NUM(51));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS", INT2NUM(52));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_TIMEOUT", INT2NUM(53));
  rb_define_const(mCreateTransferResult, "EXCEEDS_CREDITS", INT2NUM(54));
  rb_define_const(mCreateTransferResult, "EXCEEDS_DEBITS", INT2NUM(55));

}

// Definitions: Packet - tb_packet_t
static size_t rb_tb_packet_size(const void *ptr) {
  return sizeof(tb_packet_t);
}

const rb_data_type_t rb_tb_packet_type = {
  .wrap_struct_name = "tb_packet_t",
  .function = {
    .dmark = NULL,
    .dfree = RUBY_DEFAULT_FREE,
    .dsize = rb_tb_packet_size,
  },
  .data = NULL,
  .flags = RUBY_TYPED_FREE_IMMEDIATELY,
};

static VALUE rb_tb_packet_alloc(VALUE self) {
  tb_packet_t *ptr;
  return TypedData_Make_Struct(self, tb_packet_t, &rb_tb_packet_type, ptr);
}

static VALUE rb_tb_packet_initialize(int argc, VALUE *argv, VALUE self) {
  VALUE kwargs;
  rb_scan_args(argc, argv, ":", &kwargs);

  if (NIL_P(kwargs)) {
    return self;
  }

  tb_packet_t *wrapper;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, wrapper);

  VALUE keys = rb_funcall(kwargs, rb_intern("keys"), 0);
  long keys_len = RARRAY_LEN(keys);

  for (long i = 0; i < keys_len; i++) {
      VALUE key = RARRAY_AREF(keys, i);
      VALUE value = rb_hash_aref(kwargs, key);
      VALUE key_str = rb_funcall(key, rb_intern("to_s"), 0);
      const char *key_cstr = StringValueCStr(key_str);
      size_t setter_len = strlen(key_cstr) + 2; // +1 for '=', +1 for '\0'
      char *setter_name = ALLOCA_N(char, setter_len);
      snprintf(setter_name, setter_len, "%s=", key_cstr);
      ID setter_id = rb_intern(setter_name);
      if (!rb_respond_to(self, setter_id)) {
        rb_raise(rb_eNoMethodError, "undefined method '%s' for object", setter_name);
      }

      rb_funcall(self, setter_id, 1, value);
  }
  return self;
}

static VALUE rb_tb_packet_get_user_data(VALUE self) {
  rb_raise(rb_eRuntimeError, "Cannot access void* field - user_data");
  return Qnil;
}

static VALUE rb_tb_packet_set_user_data(VALUE self, VALUE val) {
  if (NIL_P(val)) {
    rb_raise(rb_eTypeError, "Expected a non nil value");
    return Qnil;
  }
  if (!RB_TYPE_P(val, T_STRING)) {
    rb_raise(rb_eTypeError, "Expected a straing");
  }
  tb_packet_t *obj;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, obj);
  if (obj->user_data != NULL) {
    rb_raise(rb_eRuntimeError, "Void* field is already set");
    return Qnil;
  }
  size_t data_size = (size_t)RSTRING_LEN(val);
  char *data = (char*)malloc(data_size);
  memcpy(data, RSTRING_PTR(val), data_size);
  obj->user_data = data;
  return val;
}

static VALUE rb_tb_packet_get_data(VALUE self) {
  rb_raise(rb_eRuntimeError, "Cannot access void* field - data");
  return Qnil;
}

static VALUE rb_tb_packet_set_data(VALUE self, VALUE val) {
  if (NIL_P(val)) {
    rb_raise(rb_eTypeError, "Expected a non nil value");
    return Qnil;
  }
  if (!RB_TYPE_P(val, T_STRING)) {
    rb_raise(rb_eTypeError, "Expected a straing");
  }
  tb_packet_t *obj;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, obj);
  if (obj->data != NULL) {
    rb_raise(rb_eRuntimeError, "Void* field is already set");
    return Qnil;
  }
  size_t data_size = (size_t)RSTRING_LEN(val);
  char *data = (char*)malloc(data_size);
  memcpy(data, RSTRING_PTR(val), data_size);
  obj->data = data;
  return val;
}

static VALUE rb_tb_packet_get_data_size(VALUE self) {
  tb_packet_t *obj;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, obj);
  return ULL2NUM(obj->data_size);
}

static VALUE rb_tb_packet_set_data_size(VALUE self, VALUE val) {
  tb_packet_t *obj;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, obj);
  obj->data_size = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_packet_get_user_tag(VALUE self) {
  tb_packet_t *obj;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, obj);
  return ULL2NUM(obj->user_tag);
}

static VALUE rb_tb_packet_set_user_tag(VALUE self, VALUE val) {
  tb_packet_t *obj;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, obj);
  obj->user_tag = (uint16_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_packet_get_operation(VALUE self) {
  tb_packet_t *obj;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, obj);
  return ULL2NUM(obj->operation);
}

static VALUE rb_tb_packet_set_operation(VALUE self, VALUE val) {
  tb_packet_t *obj;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, obj);
  obj->operation = (uint8_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_packet_get_status(VALUE self) {
  tb_packet_t *obj;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, obj);
  return ULL2NUM(obj->status);
}

static VALUE rb_tb_packet_set_status(VALUE self, VALUE val) {
  tb_packet_t *obj;
  TypedData_Get_Struct(self, tb_packet_t, &rb_tb_packet_type, obj);
  obj->status = (uint8_t)NUM2ULL(val);
  return val;
}



// Definitions: Client - tb_client_t
static size_t rb_tb_client_size(const void *ptr) {
  return sizeof(tb_client_t);
}

const rb_data_type_t rb_tb_client_type = {
  .wrap_struct_name = "tb_client_t",
  .function = {
    .dmark = NULL,
    .dfree = RUBY_DEFAULT_FREE,
    .dsize = rb_tb_client_size,
  },
  .data = NULL,
  .flags = RUBY_TYPED_FREE_IMMEDIATELY,
};

static VALUE rb_tb_client_alloc(VALUE self) {
  tb_client_t *ptr;
  return TypedData_Make_Struct(self, tb_client_t, &rb_tb_client_type, ptr);
}

static VALUE rb_tb_client_initialize(int argc, VALUE *argv, VALUE self) {
  VALUE kwargs;
  rb_scan_args(argc, argv, ":", &kwargs);

  if (NIL_P(kwargs)) {
    return self;
  }

  tb_client_t *wrapper;
  TypedData_Get_Struct(self, tb_client_t, &rb_tb_client_type, wrapper);

  VALUE keys = rb_funcall(kwargs, rb_intern("keys"), 0);
  long keys_len = RARRAY_LEN(keys);

  for (long i = 0; i < keys_len; i++) {
      VALUE key = RARRAY_AREF(keys, i);
      VALUE value = rb_hash_aref(kwargs, key);
      VALUE key_str = rb_funcall(key, rb_intern("to_s"), 0);
      const char *key_cstr = StringValueCStr(key_str);
      size_t setter_len = strlen(key_cstr) + 2; // +1 for '=', +1 for '\0'
      char *setter_name = ALLOCA_N(char, setter_len);
      snprintf(setter_name, setter_len, "%s=", key_cstr);
      ID setter_id = rb_intern(setter_name);
      if (!rb_respond_to(self, setter_id)) {
        rb_raise(rb_eNoMethodError, "undefined method '%s' for object", setter_name);
      }

      rb_funcall(self, setter_id, 1, value);
  }
  return self;
}



// Definitions: Account - tb_account_t
static size_t rb_tb_account_size(const void *ptr) {
  return sizeof(tb_account_t);
}

const rb_data_type_t rb_tb_account_type = {
  .wrap_struct_name = "tb_account_t",
  .function = {
    .dmark = NULL,
    .dfree = RUBY_DEFAULT_FREE,
    .dsize = rb_tb_account_size,
  },
  .data = NULL,
  .flags = RUBY_TYPED_FREE_IMMEDIATELY,
};

static VALUE rb_tb_account_alloc(VALUE self) {
  tb_account_t *ptr;
  return TypedData_Make_Struct(self, tb_account_t, &rb_tb_account_type, ptr);
}

static VALUE rb_tb_account_initialize(int argc, VALUE *argv, VALUE self) {
  VALUE kwargs;
  rb_scan_args(argc, argv, ":", &kwargs);

  if (NIL_P(kwargs)) {
    return self;
  }

  tb_account_t *wrapper;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, wrapper);

  VALUE keys = rb_funcall(kwargs, rb_intern("keys"), 0);
  long keys_len = RARRAY_LEN(keys);

  for (long i = 0; i < keys_len; i++) {
      VALUE key = RARRAY_AREF(keys, i);
      VALUE value = rb_hash_aref(kwargs, key);
      VALUE key_str = rb_funcall(key, rb_intern("to_s"), 0);
      const char *key_cstr = StringValueCStr(key_str);
      size_t setter_len = strlen(key_cstr) + 2; // +1 for '=', +1 for '\0'
      char *setter_name = ALLOCA_N(char, setter_len);
      snprintf(setter_name, setter_len, "%s=", key_cstr);
      ID setter_id = rb_intern(setter_name);
      if (!rb_respond_to(self, setter_id)) {
        rb_raise(rb_eNoMethodError, "undefined method '%s' for object", setter_name);
      }

      rb_funcall(self, setter_id, 1, value);
  }
  return self;
}

static VALUE rb_tb_account_get_id(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return uint128_to_hex_string(obj->id);
}

static VALUE rb_tb_account_set_id(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->id = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_get_debits_pending(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return uint128_to_hex_string(obj->debits_pending);
}

static VALUE rb_tb_account_set_debits_pending(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->debits_pending = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_get_debits_posted(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return uint128_to_hex_string(obj->debits_posted);
}

static VALUE rb_tb_account_set_debits_posted(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->debits_posted = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_get_credits_pending(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return uint128_to_hex_string(obj->credits_pending);
}

static VALUE rb_tb_account_set_credits_pending(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->credits_pending = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_get_credits_posted(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return uint128_to_hex_string(obj->credits_posted);
}

static VALUE rb_tb_account_set_credits_posted(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->credits_posted = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_get_user_data_128(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return uint128_to_hex_string(obj->user_data_128);
}

static VALUE rb_tb_account_set_user_data_128(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->user_data_128 = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_get_user_data_64(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return ULL2NUM(obj->user_data_64);
}

static VALUE rb_tb_account_set_user_data_64(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->user_data_64 = (uint64_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_get_user_data_32(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return ULL2NUM(obj->user_data_32);
}

static VALUE rb_tb_account_set_user_data_32(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->user_data_32 = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_get_ledger(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return ULL2NUM(obj->ledger);
}

static VALUE rb_tb_account_set_ledger(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->ledger = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_get_code(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return ULL2NUM(obj->code);
}

static VALUE rb_tb_account_set_code(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->code = (uint16_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_get_flags(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return ULL2NUM(obj->flags);
}

static VALUE rb_tb_account_set_flags(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->flags = (uint16_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_get_timestamp(VALUE self) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  return ULL2NUM(obj->timestamp);
}

static VALUE rb_tb_account_set_timestamp(VALUE self, VALUE val) {
  tb_account_t *obj;
  TypedData_Get_Struct(self, tb_account_t, &rb_tb_account_type, obj);
  obj->timestamp = (uint64_t)NUM2ULL(val);
  return val;
}



// Definitions: Transfer - tb_transfer_t
static size_t rb_tb_transfer_size(const void *ptr) {
  return sizeof(tb_transfer_t);
}

const rb_data_type_t rb_tb_transfer_type = {
  .wrap_struct_name = "tb_transfer_t",
  .function = {
    .dmark = NULL,
    .dfree = RUBY_DEFAULT_FREE,
    .dsize = rb_tb_transfer_size,
  },
  .data = NULL,
  .flags = RUBY_TYPED_FREE_IMMEDIATELY,
};

static VALUE rb_tb_transfer_alloc(VALUE self) {
  tb_transfer_t *ptr;
  return TypedData_Make_Struct(self, tb_transfer_t, &rb_tb_transfer_type, ptr);
}

static VALUE rb_tb_transfer_initialize(int argc, VALUE *argv, VALUE self) {
  VALUE kwargs;
  rb_scan_args(argc, argv, ":", &kwargs);

  if (NIL_P(kwargs)) {
    return self;
  }

  tb_transfer_t *wrapper;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, wrapper);

  VALUE keys = rb_funcall(kwargs, rb_intern("keys"), 0);
  long keys_len = RARRAY_LEN(keys);

  for (long i = 0; i < keys_len; i++) {
      VALUE key = RARRAY_AREF(keys, i);
      VALUE value = rb_hash_aref(kwargs, key);
      VALUE key_str = rb_funcall(key, rb_intern("to_s"), 0);
      const char *key_cstr = StringValueCStr(key_str);
      size_t setter_len = strlen(key_cstr) + 2; // +1 for '=', +1 for '\0'
      char *setter_name = ALLOCA_N(char, setter_len);
      snprintf(setter_name, setter_len, "%s=", key_cstr);
      ID setter_id = rb_intern(setter_name);
      if (!rb_respond_to(self, setter_id)) {
        rb_raise(rb_eNoMethodError, "undefined method '%s' for object", setter_name);
      }

      rb_funcall(self, setter_id, 1, value);
  }
  return self;
}

static VALUE rb_tb_transfer_get_id(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return uint128_to_hex_string(obj->id);
}

static VALUE rb_tb_transfer_set_id(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->id = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_transfer_get_debit_account_id(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return uint128_to_hex_string(obj->debit_account_id);
}

static VALUE rb_tb_transfer_set_debit_account_id(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->debit_account_id = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_transfer_get_credit_account_id(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return uint128_to_hex_string(obj->credit_account_id);
}

static VALUE rb_tb_transfer_set_credit_account_id(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->credit_account_id = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_transfer_get_amount(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return uint128_to_hex_string(obj->amount);
}

static VALUE rb_tb_transfer_set_amount(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->amount = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_transfer_get_pending_id(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return uint128_to_hex_string(obj->pending_id);
}

static VALUE rb_tb_transfer_set_pending_id(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->pending_id = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_transfer_get_user_data_128(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return uint128_to_hex_string(obj->user_data_128);
}

static VALUE rb_tb_transfer_set_user_data_128(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->user_data_128 = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_transfer_get_user_data_64(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return ULL2NUM(obj->user_data_64);
}

static VALUE rb_tb_transfer_set_user_data_64(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->user_data_64 = (uint64_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_transfer_get_user_data_32(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return ULL2NUM(obj->user_data_32);
}

static VALUE rb_tb_transfer_set_user_data_32(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->user_data_32 = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_transfer_get_timeout(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return ULL2NUM(obj->timeout);
}

static VALUE rb_tb_transfer_set_timeout(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->timeout = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_transfer_get_ledger(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return ULL2NUM(obj->ledger);
}

static VALUE rb_tb_transfer_set_ledger(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->ledger = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_transfer_get_code(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return ULL2NUM(obj->code);
}

static VALUE rb_tb_transfer_set_code(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->code = (uint16_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_transfer_get_flags(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return ULL2NUM(obj->flags);
}

static VALUE rb_tb_transfer_set_flags(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->flags = (uint16_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_transfer_get_timestamp(VALUE self) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  return ULL2NUM(obj->timestamp);
}

static VALUE rb_tb_transfer_set_timestamp(VALUE self, VALUE val) {
  tb_transfer_t *obj;
  TypedData_Get_Struct(self, tb_transfer_t, &rb_tb_transfer_type, obj);
  obj->timestamp = (uint64_t)NUM2ULL(val);
  return val;
}



// Definitions: AccountFilter - tb_account_filter_t
static size_t rb_tb_account_filter_size(const void *ptr) {
  return sizeof(tb_account_filter_t);
}

const rb_data_type_t rb_tb_account_filter_type = {
  .wrap_struct_name = "tb_account_filter_t",
  .function = {
    .dmark = NULL,
    .dfree = RUBY_DEFAULT_FREE,
    .dsize = rb_tb_account_filter_size,
  },
  .data = NULL,
  .flags = RUBY_TYPED_FREE_IMMEDIATELY,
};

static VALUE rb_tb_account_filter_alloc(VALUE self) {
  tb_account_filter_t *ptr;
  return TypedData_Make_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, ptr);
}

static VALUE rb_tb_account_filter_initialize(int argc, VALUE *argv, VALUE self) {
  VALUE kwargs;
  rb_scan_args(argc, argv, ":", &kwargs);

  if (NIL_P(kwargs)) {
    return self;
  }

  tb_account_filter_t *wrapper;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, wrapper);

  VALUE keys = rb_funcall(kwargs, rb_intern("keys"), 0);
  long keys_len = RARRAY_LEN(keys);

  for (long i = 0; i < keys_len; i++) {
      VALUE key = RARRAY_AREF(keys, i);
      VALUE value = rb_hash_aref(kwargs, key);
      VALUE key_str = rb_funcall(key, rb_intern("to_s"), 0);
      const char *key_cstr = StringValueCStr(key_str);
      size_t setter_len = strlen(key_cstr) + 2; // +1 for '=', +1 for '\0'
      char *setter_name = ALLOCA_N(char, setter_len);
      snprintf(setter_name, setter_len, "%s=", key_cstr);
      ID setter_id = rb_intern(setter_name);
      if (!rb_respond_to(self, setter_id)) {
        rb_raise(rb_eNoMethodError, "undefined method '%s' for object", setter_name);
      }

      rb_funcall(self, setter_id, 1, value);
  }
  return self;
}

static VALUE rb_tb_account_filter_get_account_id(VALUE self) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  return uint128_to_hex_string(obj->account_id);
}

static VALUE rb_tb_account_filter_set_account_id(VALUE self, VALUE val) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  obj->account_id = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_filter_get_user_data_128(VALUE self) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  return uint128_to_hex_string(obj->user_data_128);
}

static VALUE rb_tb_account_filter_set_user_data_128(VALUE self, VALUE val) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  obj->user_data_128 = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_filter_get_user_data_64(VALUE self) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  return ULL2NUM(obj->user_data_64);
}

static VALUE rb_tb_account_filter_set_user_data_64(VALUE self, VALUE val) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  obj->user_data_64 = (uint64_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_filter_get_user_data_32(VALUE self) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  return ULL2NUM(obj->user_data_32);
}

static VALUE rb_tb_account_filter_set_user_data_32(VALUE self, VALUE val) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  obj->user_data_32 = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_filter_get_code(VALUE self) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  return ULL2NUM(obj->code);
}

static VALUE rb_tb_account_filter_set_code(VALUE self, VALUE val) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  obj->code = (uint16_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_filter_get_timestamp_min(VALUE self) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  return ULL2NUM(obj->timestamp_min);
}

static VALUE rb_tb_account_filter_set_timestamp_min(VALUE self, VALUE val) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  obj->timestamp_min = (uint64_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_filter_get_timestamp_max(VALUE self) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  return ULL2NUM(obj->timestamp_max);
}

static VALUE rb_tb_account_filter_set_timestamp_max(VALUE self, VALUE val) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  obj->timestamp_max = (uint64_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_filter_get_limit(VALUE self) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  return ULL2NUM(obj->limit);
}

static VALUE rb_tb_account_filter_set_limit(VALUE self, VALUE val) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  obj->limit = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_account_filter_get_flags(VALUE self) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  return ULL2NUM(obj->flags);
}

static VALUE rb_tb_account_filter_set_flags(VALUE self, VALUE val) {
  tb_account_filter_t *obj;
  TypedData_Get_Struct(self, tb_account_filter_t, &rb_tb_account_filter_type, obj);
  obj->flags = (uint32_t)NUM2ULL(val);
  return val;
}



// Definitions: AccountBalance - tb_account_balance_t
static size_t rb_tb_account_balance_size(const void *ptr) {
  return sizeof(tb_account_balance_t);
}

const rb_data_type_t rb_tb_account_balance_type = {
  .wrap_struct_name = "tb_account_balance_t",
  .function = {
    .dmark = NULL,
    .dfree = RUBY_DEFAULT_FREE,
    .dsize = rb_tb_account_balance_size,
  },
  .data = NULL,
  .flags = RUBY_TYPED_FREE_IMMEDIATELY,
};

static VALUE rb_tb_account_balance_alloc(VALUE self) {
  tb_account_balance_t *ptr;
  return TypedData_Make_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, ptr);
}

static VALUE rb_tb_account_balance_initialize(int argc, VALUE *argv, VALUE self) {
  VALUE kwargs;
  rb_scan_args(argc, argv, ":", &kwargs);

  if (NIL_P(kwargs)) {
    return self;
  }

  tb_account_balance_t *wrapper;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, wrapper);

  VALUE keys = rb_funcall(kwargs, rb_intern("keys"), 0);
  long keys_len = RARRAY_LEN(keys);

  for (long i = 0; i < keys_len; i++) {
      VALUE key = RARRAY_AREF(keys, i);
      VALUE value = rb_hash_aref(kwargs, key);
      VALUE key_str = rb_funcall(key, rb_intern("to_s"), 0);
      const char *key_cstr = StringValueCStr(key_str);
      size_t setter_len = strlen(key_cstr) + 2; // +1 for '=', +1 for '\0'
      char *setter_name = ALLOCA_N(char, setter_len);
      snprintf(setter_name, setter_len, "%s=", key_cstr);
      ID setter_id = rb_intern(setter_name);
      if (!rb_respond_to(self, setter_id)) {
        rb_raise(rb_eNoMethodError, "undefined method '%s' for object", setter_name);
      }

      rb_funcall(self, setter_id, 1, value);
  }
  return self;
}

static VALUE rb_tb_account_balance_get_debits_pending(VALUE self) {
  tb_account_balance_t *obj;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, obj);
  return uint128_to_hex_string(obj->debits_pending);
}

static VALUE rb_tb_account_balance_set_debits_pending(VALUE self, VALUE val) {
  tb_account_balance_t *obj;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, obj);
  obj->debits_pending = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_balance_get_debits_posted(VALUE self) {
  tb_account_balance_t *obj;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, obj);
  return uint128_to_hex_string(obj->debits_posted);
}

static VALUE rb_tb_account_balance_set_debits_posted(VALUE self, VALUE val) {
  tb_account_balance_t *obj;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, obj);
  obj->debits_posted = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_balance_get_credits_pending(VALUE self) {
  tb_account_balance_t *obj;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, obj);
  return uint128_to_hex_string(obj->credits_pending);
}

static VALUE rb_tb_account_balance_set_credits_pending(VALUE self, VALUE val) {
  tb_account_balance_t *obj;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, obj);
  obj->credits_pending = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_balance_get_credits_posted(VALUE self) {
  tb_account_balance_t *obj;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, obj);
  return uint128_to_hex_string(obj->credits_posted);
}

static VALUE rb_tb_account_balance_set_credits_posted(VALUE self, VALUE val) {
  tb_account_balance_t *obj;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, obj);
  obj->credits_posted = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_account_balance_get_timestamp(VALUE self) {
  tb_account_balance_t *obj;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, obj);
  return ULL2NUM(obj->timestamp);
}

static VALUE rb_tb_account_balance_set_timestamp(VALUE self, VALUE val) {
  tb_account_balance_t *obj;
  TypedData_Get_Struct(self, tb_account_balance_t, &rb_tb_account_balance_type, obj);
  obj->timestamp = (uint64_t)NUM2ULL(val);
  return val;
}



// Definitions: QueryFilter - tb_query_filter_t
static size_t rb_tb_query_filter_size(const void *ptr) {
  return sizeof(tb_query_filter_t);
}

const rb_data_type_t rb_tb_query_filter_type = {
  .wrap_struct_name = "tb_query_filter_t",
  .function = {
    .dmark = NULL,
    .dfree = RUBY_DEFAULT_FREE,
    .dsize = rb_tb_query_filter_size,
  },
  .data = NULL,
  .flags = RUBY_TYPED_FREE_IMMEDIATELY,
};

static VALUE rb_tb_query_filter_alloc(VALUE self) {
  tb_query_filter_t *ptr;
  return TypedData_Make_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, ptr);
}

static VALUE rb_tb_query_filter_initialize(int argc, VALUE *argv, VALUE self) {
  VALUE kwargs;
  rb_scan_args(argc, argv, ":", &kwargs);

  if (NIL_P(kwargs)) {
    return self;
  }

  tb_query_filter_t *wrapper;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, wrapper);

  VALUE keys = rb_funcall(kwargs, rb_intern("keys"), 0);
  long keys_len = RARRAY_LEN(keys);

  for (long i = 0; i < keys_len; i++) {
      VALUE key = RARRAY_AREF(keys, i);
      VALUE value = rb_hash_aref(kwargs, key);
      VALUE key_str = rb_funcall(key, rb_intern("to_s"), 0);
      const char *key_cstr = StringValueCStr(key_str);
      size_t setter_len = strlen(key_cstr) + 2; // +1 for '=', +1 for '\0'
      char *setter_name = ALLOCA_N(char, setter_len);
      snprintf(setter_name, setter_len, "%s=", key_cstr);
      ID setter_id = rb_intern(setter_name);
      if (!rb_respond_to(self, setter_id)) {
        rb_raise(rb_eNoMethodError, "undefined method '%s' for object", setter_name);
      }

      rb_funcall(self, setter_id, 1, value);
  }
  return self;
}

static VALUE rb_tb_query_filter_get_user_data_128(VALUE self) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  return uint128_to_hex_string(obj->user_data_128);
}

static VALUE rb_tb_query_filter_set_user_data_128(VALUE self, VALUE val) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  obj->user_data_128 = hex_string_to_uint128(val);
  return val;
}

static VALUE rb_tb_query_filter_get_user_data_64(VALUE self) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  return ULL2NUM(obj->user_data_64);
}

static VALUE rb_tb_query_filter_set_user_data_64(VALUE self, VALUE val) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  obj->user_data_64 = (uint64_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_query_filter_get_user_data_32(VALUE self) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  return ULL2NUM(obj->user_data_32);
}

static VALUE rb_tb_query_filter_set_user_data_32(VALUE self, VALUE val) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  obj->user_data_32 = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_query_filter_get_ledger(VALUE self) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  return ULL2NUM(obj->ledger);
}

static VALUE rb_tb_query_filter_set_ledger(VALUE self, VALUE val) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  obj->ledger = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_query_filter_get_code(VALUE self) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  return ULL2NUM(obj->code);
}

static VALUE rb_tb_query_filter_set_code(VALUE self, VALUE val) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  obj->code = (uint16_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_query_filter_get_timestamp_min(VALUE self) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  return ULL2NUM(obj->timestamp_min);
}

static VALUE rb_tb_query_filter_set_timestamp_min(VALUE self, VALUE val) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  obj->timestamp_min = (uint64_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_query_filter_get_timestamp_max(VALUE self) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  return ULL2NUM(obj->timestamp_max);
}

static VALUE rb_tb_query_filter_set_timestamp_max(VALUE self, VALUE val) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  obj->timestamp_max = (uint64_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_query_filter_get_limit(VALUE self) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  return ULL2NUM(obj->limit);
}

static VALUE rb_tb_query_filter_set_limit(VALUE self, VALUE val) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  obj->limit = (uint32_t)NUM2ULL(val);
  return val;
}

static VALUE rb_tb_query_filter_get_flags(VALUE self) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  return ULL2NUM(obj->flags);
}

static VALUE rb_tb_query_filter_set_flags(VALUE self, VALUE val) {
  tb_query_filter_t *obj;
  TypedData_Get_Struct(self, tb_query_filter_t, &rb_tb_query_filter_type, obj);
  obj->flags = (uint32_t)NUM2ULL(val);
  return val;
}



//Ruby method accessors
void tb_define_ruby_accessors(VALUE module) {

  VALUE m_Packet_klass = rb_define_class_under(module, "Packet", rb_cObject);
  rb_define_alloc_func(m_Packet_klass, rb_tb_packet_alloc);
  rb_define_method(m_Packet_klass, "initialize", rb_tb_packet_initialize, -1);
  rb_define_method(m_Packet_klass, "user_data",  rb_tb_packet_get_user_data, 0);
  rb_define_method(m_Packet_klass, "user_data=",  rb_tb_packet_set_user_data, 1);
  rb_define_method(m_Packet_klass, "data",  rb_tb_packet_get_data, 0);
  rb_define_method(m_Packet_klass, "data=",  rb_tb_packet_set_data, 1);
  rb_define_method(m_Packet_klass, "data_size",  rb_tb_packet_get_data_size, 0);
  rb_define_method(m_Packet_klass, "data_size=",  rb_tb_packet_set_data_size, 1);
  rb_define_method(m_Packet_klass, "user_tag",  rb_tb_packet_get_user_tag, 0);
  rb_define_method(m_Packet_klass, "user_tag=",  rb_tb_packet_set_user_tag, 1);
  rb_define_method(m_Packet_klass, "operation",  rb_tb_packet_get_operation, 0);
  rb_define_method(m_Packet_klass, "operation=",  rb_tb_packet_set_operation, 1);
  rb_define_method(m_Packet_klass, "status",  rb_tb_packet_get_status, 0);
  rb_define_method(m_Packet_klass, "status=",  rb_tb_packet_set_status, 1);

  VALUE m_Client_klass = rb_define_class_under(module, "Client", rb_cObject);
  rb_define_alloc_func(m_Client_klass, rb_tb_client_alloc);
  rb_define_method(m_Client_klass, "initialize", rb_tb_client_initialize, -1);

  VALUE m_Account_klass = rb_define_class_under(module, "Account", rb_cObject);
  rb_define_alloc_func(m_Account_klass, rb_tb_account_alloc);
  rb_define_method(m_Account_klass, "initialize", rb_tb_account_initialize, -1);
  rb_define_method(m_Account_klass, "id",  rb_tb_account_get_id, 0);
  rb_define_method(m_Account_klass, "id=",  rb_tb_account_set_id, 1);
  rb_define_method(m_Account_klass, "debits_pending",  rb_tb_account_get_debits_pending, 0);
  rb_define_method(m_Account_klass, "debits_pending=",  rb_tb_account_set_debits_pending, 1);
  rb_define_method(m_Account_klass, "debits_posted",  rb_tb_account_get_debits_posted, 0);
  rb_define_method(m_Account_klass, "debits_posted=",  rb_tb_account_set_debits_posted, 1);
  rb_define_method(m_Account_klass, "credits_pending",  rb_tb_account_get_credits_pending, 0);
  rb_define_method(m_Account_klass, "credits_pending=",  rb_tb_account_set_credits_pending, 1);
  rb_define_method(m_Account_klass, "credits_posted",  rb_tb_account_get_credits_posted, 0);
  rb_define_method(m_Account_klass, "credits_posted=",  rb_tb_account_set_credits_posted, 1);
  rb_define_method(m_Account_klass, "user_data_128",  rb_tb_account_get_user_data_128, 0);
  rb_define_method(m_Account_klass, "user_data_128=",  rb_tb_account_set_user_data_128, 1);
  rb_define_method(m_Account_klass, "user_data_64",  rb_tb_account_get_user_data_64, 0);
  rb_define_method(m_Account_klass, "user_data_64=",  rb_tb_account_set_user_data_64, 1);
  rb_define_method(m_Account_klass, "user_data_32",  rb_tb_account_get_user_data_32, 0);
  rb_define_method(m_Account_klass, "user_data_32=",  rb_tb_account_set_user_data_32, 1);
  rb_define_method(m_Account_klass, "ledger",  rb_tb_account_get_ledger, 0);
  rb_define_method(m_Account_klass, "ledger=",  rb_tb_account_set_ledger, 1);
  rb_define_method(m_Account_klass, "code",  rb_tb_account_get_code, 0);
  rb_define_method(m_Account_klass, "code=",  rb_tb_account_set_code, 1);
  rb_define_method(m_Account_klass, "flags",  rb_tb_account_get_flags, 0);
  rb_define_method(m_Account_klass, "flags=",  rb_tb_account_set_flags, 1);
  rb_define_method(m_Account_klass, "timestamp",  rb_tb_account_get_timestamp, 0);
  rb_define_method(m_Account_klass, "timestamp=",  rb_tb_account_set_timestamp, 1);

  VALUE m_Transfer_klass = rb_define_class_under(module, "Transfer", rb_cObject);
  rb_define_alloc_func(m_Transfer_klass, rb_tb_transfer_alloc);
  rb_define_method(m_Transfer_klass, "initialize", rb_tb_transfer_initialize, -1);
  rb_define_method(m_Transfer_klass, "id",  rb_tb_transfer_get_id, 0);
  rb_define_method(m_Transfer_klass, "id=",  rb_tb_transfer_set_id, 1);
  rb_define_method(m_Transfer_klass, "debit_account_id",  rb_tb_transfer_get_debit_account_id, 0);
  rb_define_method(m_Transfer_klass, "debit_account_id=",  rb_tb_transfer_set_debit_account_id, 1);
  rb_define_method(m_Transfer_klass, "credit_account_id",  rb_tb_transfer_get_credit_account_id, 0);
  rb_define_method(m_Transfer_klass, "credit_account_id=",  rb_tb_transfer_set_credit_account_id, 1);
  rb_define_method(m_Transfer_klass, "amount",  rb_tb_transfer_get_amount, 0);
  rb_define_method(m_Transfer_klass, "amount=",  rb_tb_transfer_set_amount, 1);
  rb_define_method(m_Transfer_klass, "pending_id",  rb_tb_transfer_get_pending_id, 0);
  rb_define_method(m_Transfer_klass, "pending_id=",  rb_tb_transfer_set_pending_id, 1);
  rb_define_method(m_Transfer_klass, "user_data_128",  rb_tb_transfer_get_user_data_128, 0);
  rb_define_method(m_Transfer_klass, "user_data_128=",  rb_tb_transfer_set_user_data_128, 1);
  rb_define_method(m_Transfer_klass, "user_data_64",  rb_tb_transfer_get_user_data_64, 0);
  rb_define_method(m_Transfer_klass, "user_data_64=",  rb_tb_transfer_set_user_data_64, 1);
  rb_define_method(m_Transfer_klass, "user_data_32",  rb_tb_transfer_get_user_data_32, 0);
  rb_define_method(m_Transfer_klass, "user_data_32=",  rb_tb_transfer_set_user_data_32, 1);
  rb_define_method(m_Transfer_klass, "timeout",  rb_tb_transfer_get_timeout, 0);
  rb_define_method(m_Transfer_klass, "timeout=",  rb_tb_transfer_set_timeout, 1);
  rb_define_method(m_Transfer_klass, "ledger",  rb_tb_transfer_get_ledger, 0);
  rb_define_method(m_Transfer_klass, "ledger=",  rb_tb_transfer_set_ledger, 1);
  rb_define_method(m_Transfer_klass, "code",  rb_tb_transfer_get_code, 0);
  rb_define_method(m_Transfer_klass, "code=",  rb_tb_transfer_set_code, 1);
  rb_define_method(m_Transfer_klass, "flags",  rb_tb_transfer_get_flags, 0);
  rb_define_method(m_Transfer_klass, "flags=",  rb_tb_transfer_set_flags, 1);
  rb_define_method(m_Transfer_klass, "timestamp",  rb_tb_transfer_get_timestamp, 0);
  rb_define_method(m_Transfer_klass, "timestamp=",  rb_tb_transfer_set_timestamp, 1);

  VALUE m_AccountFilter_klass = rb_define_class_under(module, "AccountFilter", rb_cObject);
  rb_define_alloc_func(m_AccountFilter_klass, rb_tb_account_filter_alloc);
  rb_define_method(m_AccountFilter_klass, "initialize", rb_tb_account_filter_initialize, -1);
  rb_define_method(m_AccountFilter_klass, "account_id",  rb_tb_account_filter_get_account_id, 0);
  rb_define_method(m_AccountFilter_klass, "account_id=",  rb_tb_account_filter_set_account_id, 1);
  rb_define_method(m_AccountFilter_klass, "user_data_128",  rb_tb_account_filter_get_user_data_128, 0);
  rb_define_method(m_AccountFilter_klass, "user_data_128=",  rb_tb_account_filter_set_user_data_128, 1);
  rb_define_method(m_AccountFilter_klass, "user_data_64",  rb_tb_account_filter_get_user_data_64, 0);
  rb_define_method(m_AccountFilter_klass, "user_data_64=",  rb_tb_account_filter_set_user_data_64, 1);
  rb_define_method(m_AccountFilter_klass, "user_data_32",  rb_tb_account_filter_get_user_data_32, 0);
  rb_define_method(m_AccountFilter_klass, "user_data_32=",  rb_tb_account_filter_set_user_data_32, 1);
  rb_define_method(m_AccountFilter_klass, "code",  rb_tb_account_filter_get_code, 0);
  rb_define_method(m_AccountFilter_klass, "code=",  rb_tb_account_filter_set_code, 1);
  rb_define_method(m_AccountFilter_klass, "timestamp_min",  rb_tb_account_filter_get_timestamp_min, 0);
  rb_define_method(m_AccountFilter_klass, "timestamp_min=",  rb_tb_account_filter_set_timestamp_min, 1);
  rb_define_method(m_AccountFilter_klass, "timestamp_max",  rb_tb_account_filter_get_timestamp_max, 0);
  rb_define_method(m_AccountFilter_klass, "timestamp_max=",  rb_tb_account_filter_set_timestamp_max, 1);
  rb_define_method(m_AccountFilter_klass, "limit",  rb_tb_account_filter_get_limit, 0);
  rb_define_method(m_AccountFilter_klass, "limit=",  rb_tb_account_filter_set_limit, 1);
  rb_define_method(m_AccountFilter_klass, "flags",  rb_tb_account_filter_get_flags, 0);
  rb_define_method(m_AccountFilter_klass, "flags=",  rb_tb_account_filter_set_flags, 1);

  VALUE m_AccountBalance_klass = rb_define_class_under(module, "AccountBalance", rb_cObject);
  rb_define_alloc_func(m_AccountBalance_klass, rb_tb_account_balance_alloc);
  rb_define_method(m_AccountBalance_klass, "initialize", rb_tb_account_balance_initialize, -1);
  rb_define_method(m_AccountBalance_klass, "debits_pending",  rb_tb_account_balance_get_debits_pending, 0);
  rb_define_method(m_AccountBalance_klass, "debits_pending=",  rb_tb_account_balance_set_debits_pending, 1);
  rb_define_method(m_AccountBalance_klass, "debits_posted",  rb_tb_account_balance_get_debits_posted, 0);
  rb_define_method(m_AccountBalance_klass, "debits_posted=",  rb_tb_account_balance_set_debits_posted, 1);
  rb_define_method(m_AccountBalance_klass, "credits_pending",  rb_tb_account_balance_get_credits_pending, 0);
  rb_define_method(m_AccountBalance_klass, "credits_pending=",  rb_tb_account_balance_set_credits_pending, 1);
  rb_define_method(m_AccountBalance_klass, "credits_posted",  rb_tb_account_balance_get_credits_posted, 0);
  rb_define_method(m_AccountBalance_klass, "credits_posted=",  rb_tb_account_balance_set_credits_posted, 1);
  rb_define_method(m_AccountBalance_klass, "timestamp",  rb_tb_account_balance_get_timestamp, 0);
  rb_define_method(m_AccountBalance_klass, "timestamp=",  rb_tb_account_balance_set_timestamp, 1);

  VALUE m_QueryFilter_klass = rb_define_class_under(module, "QueryFilter", rb_cObject);
  rb_define_alloc_func(m_QueryFilter_klass, rb_tb_query_filter_alloc);
  rb_define_method(m_QueryFilter_klass, "initialize", rb_tb_query_filter_initialize, -1);
  rb_define_method(m_QueryFilter_klass, "user_data_128",  rb_tb_query_filter_get_user_data_128, 0);
  rb_define_method(m_QueryFilter_klass, "user_data_128=",  rb_tb_query_filter_set_user_data_128, 1);
  rb_define_method(m_QueryFilter_klass, "user_data_64",  rb_tb_query_filter_get_user_data_64, 0);
  rb_define_method(m_QueryFilter_klass, "user_data_64=",  rb_tb_query_filter_set_user_data_64, 1);
  rb_define_method(m_QueryFilter_klass, "user_data_32",  rb_tb_query_filter_get_user_data_32, 0);
  rb_define_method(m_QueryFilter_klass, "user_data_32=",  rb_tb_query_filter_set_user_data_32, 1);
  rb_define_method(m_QueryFilter_klass, "ledger",  rb_tb_query_filter_get_ledger, 0);
  rb_define_method(m_QueryFilter_klass, "ledger=",  rb_tb_query_filter_set_ledger, 1);
  rb_define_method(m_QueryFilter_klass, "code",  rb_tb_query_filter_get_code, 0);
  rb_define_method(m_QueryFilter_klass, "code=",  rb_tb_query_filter_set_code, 1);
  rb_define_method(m_QueryFilter_klass, "timestamp_min",  rb_tb_query_filter_get_timestamp_min, 0);
  rb_define_method(m_QueryFilter_klass, "timestamp_min=",  rb_tb_query_filter_set_timestamp_min, 1);
  rb_define_method(m_QueryFilter_klass, "timestamp_max",  rb_tb_query_filter_get_timestamp_max, 0);
  rb_define_method(m_QueryFilter_klass, "timestamp_max=",  rb_tb_query_filter_set_timestamp_max, 1);
  rb_define_method(m_QueryFilter_klass, "limit",  rb_tb_query_filter_get_limit, 0);
  rb_define_method(m_QueryFilter_klass, "limit=",  rb_tb_query_filter_set_limit, 1);
  rb_define_method(m_QueryFilter_klass, "flags",  rb_tb_query_filter_get_flags, 0);
  rb_define_method(m_QueryFilter_klass, "flags=",  rb_tb_query_filter_set_flags, 1);
}
