//////////////////////////////////////////////////////////////
// This file was auto-generated by ruby_native_bindings.zig //
//              Do not manually modify.                     //
//////////////////////////////////////////////////////////////

#include <ruby.h>
#include "tb_client.h"
#include "tigerbeetle/shared.c"

void Init_tigerbeetle() {
  VALUE mTigerBeetle = rb_define_module("TigerBeetle");
  VALUE mTigerBeetleBindings = rb_define_module_under(mTigerBeetle, "Bindings");

  VALUE mOperation = rb_define_module_under(mTigerBeetleBindings, "Operation");
  rb_define_const(mOperation, "PULSE", INT2NUM(128));
  rb_define_const(mOperation, "GET_EVENTS", INT2NUM(137));
  rb_define_const(mOperation, "CREATE_ACCOUNTS", INT2NUM(138));
  rb_define_const(mOperation, "CREATE_TRANSFERS", INT2NUM(139));
  rb_define_const(mOperation, "LOOKUP_ACCOUNTS", INT2NUM(140));
  rb_define_const(mOperation, "LOOKUP_TRANSFERS", INT2NUM(141));
  rb_define_const(mOperation, "GET_ACCOUNT_TRANSFERS", INT2NUM(142));
  rb_define_const(mOperation, "GET_ACCOUNT_BALANCES", INT2NUM(143));
  rb_define_const(mOperation, "QUERY_ACCOUNTS", INT2NUM(144));
  rb_define_const(mOperation, "QUERY_TRANSFERS", INT2NUM(145));

  VALUE mPacketStatus = rb_define_module_under(mTigerBeetleBindings, "PacketStatus");
  rb_define_const(mPacketStatus, "OK", INT2NUM(0));
  rb_define_const(mPacketStatus, "TOO_MUCH_DATA", INT2NUM(1));
  rb_define_const(mPacketStatus, "CLIENT_EVICTED", INT2NUM(2));
  rb_define_const(mPacketStatus, "CLIENT_RELEASE_TOO_LOW", INT2NUM(3));
  rb_define_const(mPacketStatus, "CLIENT_RELEASE_TOO_HIGH", INT2NUM(4));
  rb_define_const(mPacketStatus, "CLIENT_SHUTDOWN", INT2NUM(5));
  rb_define_const(mPacketStatus, "INVALID_OPERATION", INT2NUM(6));
  rb_define_const(mPacketStatus, "INVALID_DATA_SIZE", INT2NUM(7));

  VALUE mInitStatus = rb_define_module_under(mTigerBeetleBindings, "InitStatus");
  rb_define_const(mInitStatus, "SUCCESS", INT2NUM(0));
  rb_define_const(mInitStatus, "UNEXPECTED", INT2NUM(1));
  rb_define_const(mInitStatus, "OUT_OF_MEMORY", INT2NUM(2));
  rb_define_const(mInitStatus, "ADDRESS_INVALID", INT2NUM(3));
  rb_define_const(mInitStatus, "ADDRESS_LIMIT_EXCEEDED", INT2NUM(4));
  rb_define_const(mInitStatus, "SYSTEM_RESOURCES", INT2NUM(5));
  rb_define_const(mInitStatus, "NETWORK_SUBSYSTEM", INT2NUM(6));

  VALUE mClientStatus = rb_define_module_under(mTigerBeetleBindings, "ClientStatus");
  rb_define_const(mClientStatus, "OK", INT2NUM(0));
  rb_define_const(mClientStatus, "INVALID", INT2NUM(1));

  VALUE mLogLevel = rb_define_module_under(mTigerBeetleBindings, "LogLevel");
  rb_define_const(mLogLevel, "ERR", INT2NUM(0));
  rb_define_const(mLogLevel, "WARN", INT2NUM(1));
  rb_define_const(mLogLevel, "INFO", INT2NUM(2));
  rb_define_const(mLogLevel, "DEBUG", INT2NUM(3));

  VALUE mRegisterLogCallbackStatus = rb_define_module_under(mTigerBeetleBindings, "RegisterLogCallbackStatus");
  rb_define_const(mRegisterLogCallbackStatus, "SUCCESS", INT2NUM(0));
  rb_define_const(mRegisterLogCallbackStatus, "ALREADY_REGISTERED", INT2NUM(1));
  rb_define_const(mRegisterLogCallbackStatus, "NOT_REGISTERED", INT2NUM(2));

  VALUE mAccountFlags = rb_define_module_under(mTigerBeetleBindings, "AccountFlags");
  rb_define_const(mAccountFlags, "LINKED", INT2NUM(1 << 0));
  rb_define_const(mAccountFlags, "DEBITS_MUST_NOT_EXCEED_CREDITS", INT2NUM(1 << 1));
  rb_define_const(mAccountFlags, "CREDITS_MUST_NOT_EXCEED_DEBITS", INT2NUM(1 << 2));
  rb_define_const(mAccountFlags, "HISTORY", INT2NUM(1 << 3));
  rb_define_const(mAccountFlags, "IMPORTED", INT2NUM(1 << 4));
  rb_define_const(mAccountFlags, "CLOSED", INT2NUM(1 << 5));

  VALUE mTransferFlags = rb_define_module_under(mTigerBeetleBindings, "TransferFlags");
  rb_define_const(mTransferFlags, "LINKED", INT2NUM(1 << 0));
  rb_define_const(mTransferFlags, "PENDING", INT2NUM(1 << 1));
  rb_define_const(mTransferFlags, "POST_PENDING_TRANSFER", INT2NUM(1 << 2));
  rb_define_const(mTransferFlags, "VOID_PENDING_TRANSFER", INT2NUM(1 << 3));
  rb_define_const(mTransferFlags, "BALANCING_DEBIT", INT2NUM(1 << 4));
  rb_define_const(mTransferFlags, "BALANCING_CREDIT", INT2NUM(1 << 5));
  rb_define_const(mTransferFlags, "CLOSING_DEBIT", INT2NUM(1 << 6));
  rb_define_const(mTransferFlags, "CLOSING_CREDIT", INT2NUM(1 << 7));
  rb_define_const(mTransferFlags, "IMPORTED", INT2NUM(1 << 8));

  VALUE mAccountFilterFlags = rb_define_module_under(mTigerBeetleBindings, "AccountFilterFlags");
  rb_define_const(mAccountFilterFlags, "DEBITS", INT2NUM(1 << 0));
  rb_define_const(mAccountFilterFlags, "CREDITS", INT2NUM(1 << 1));
  rb_define_const(mAccountFilterFlags, "REVERSED", INT2NUM(1 << 2));

  VALUE mQueryFilterFlags = rb_define_module_under(mTigerBeetleBindings, "QueryFilterFlags");
  rb_define_const(mQueryFilterFlags, "REVERSED", INT2NUM(1 << 0));

  VALUE mCreateAccountResult = rb_define_module_under(mTigerBeetleBindings, "CreateAccountResult");
  rb_define_const(mCreateAccountResult, "OK", INT2NUM(0));
  rb_define_const(mCreateAccountResult, "LINKED_EVENT_FAILED", INT2NUM(1));
  rb_define_const(mCreateAccountResult, "LINKED_EVENT_CHAIN_OPEN", INT2NUM(2));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_EXPECTED", INT2NUM(22));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_NOT_EXPECTED", INT2NUM(23));
  rb_define_const(mCreateAccountResult, "TIMESTAMP_MUST_BE_ZERO", INT2NUM(3));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE", INT2NUM(24));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE", INT2NUM(25));
  rb_define_const(mCreateAccountResult, "RESERVED_FIELD", INT2NUM(4));
  rb_define_const(mCreateAccountResult, "RESERVED_FLAG", INT2NUM(5));
  rb_define_const(mCreateAccountResult, "ID_MUST_NOT_BE_ZERO", INT2NUM(6));
  rb_define_const(mCreateAccountResult, "ID_MUST_NOT_BE_INT_MAX", INT2NUM(7));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_FLAGS", INT2NUM(15));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_128", INT2NUM(16));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_64", INT2NUM(17));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_32", INT2NUM(18));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_LEDGER", INT2NUM(19));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_CODE", INT2NUM(20));
  rb_define_const(mCreateAccountResult, "EXISTS", INT2NUM(21));
  rb_define_const(mCreateAccountResult, "FLAGS_ARE_MUTUALLY_EXCLUSIVE", INT2NUM(8));
  rb_define_const(mCreateAccountResult, "DEBITS_PENDING_MUST_BE_ZERO", INT2NUM(9));
  rb_define_const(mCreateAccountResult, "DEBITS_POSTED_MUST_BE_ZERO", INT2NUM(10));
  rb_define_const(mCreateAccountResult, "CREDITS_PENDING_MUST_BE_ZERO", INT2NUM(11));
  rb_define_const(mCreateAccountResult, "CREDITS_POSTED_MUST_BE_ZERO", INT2NUM(12));
  rb_define_const(mCreateAccountResult, "LEDGER_MUST_NOT_BE_ZERO", INT2NUM(13));
  rb_define_const(mCreateAccountResult, "CODE_MUST_NOT_BE_ZERO", INT2NUM(14));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS", INT2NUM(26));

  VALUE mCreateTransferResult = rb_define_module_under(mTigerBeetleBindings, "CreateTransferResult");
  rb_define_const(mCreateTransferResult, "OK", INT2NUM(0));
  rb_define_const(mCreateTransferResult, "LINKED_EVENT_FAILED", INT2NUM(1));
  rb_define_const(mCreateTransferResult, "LINKED_EVENT_CHAIN_OPEN", INT2NUM(2));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_EXPECTED", INT2NUM(56));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_NOT_EXPECTED", INT2NUM(57));
  rb_define_const(mCreateTransferResult, "TIMESTAMP_MUST_BE_ZERO", INT2NUM(3));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE", INT2NUM(58));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE", INT2NUM(59));
  rb_define_const(mCreateTransferResult, "RESERVED_FLAG", INT2NUM(4));
  rb_define_const(mCreateTransferResult, "ID_MUST_NOT_BE_ZERO", INT2NUM(5));
  rb_define_const(mCreateTransferResult, "ID_MUST_NOT_BE_INT_MAX", INT2NUM(6));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_FLAGS", INT2NUM(36));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_PENDING_ID", INT2NUM(40));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_TIMEOUT", INT2NUM(44));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_DEBIT_ACCOUNT_ID", INT2NUM(37));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_CREDIT_ACCOUNT_ID", INT2NUM(38));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_AMOUNT", INT2NUM(39));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_128", INT2NUM(41));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_64", INT2NUM(42));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_32", INT2NUM(43));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_LEDGER", INT2NUM(67));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_CODE", INT2NUM(45));
  rb_define_const(mCreateTransferResult, "EXISTS", INT2NUM(46));
  rb_define_const(mCreateTransferResult, "ID_ALREADY_FAILED", INT2NUM(68));
  rb_define_const(mCreateTransferResult, "FLAGS_ARE_MUTUALLY_EXCLUSIVE", INT2NUM(7));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ID_MUST_NOT_BE_ZERO", INT2NUM(8));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX", INT2NUM(9));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ID_MUST_NOT_BE_ZERO", INT2NUM(10));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX", INT2NUM(11));
  rb_define_const(mCreateTransferResult, "ACCOUNTS_MUST_BE_DIFFERENT", INT2NUM(12));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_BE_ZERO", INT2NUM(13));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_NOT_BE_ZERO", INT2NUM(14));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_NOT_BE_INT_MAX", INT2NUM(15));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_BE_DIFFERENT", INT2NUM(16));
  rb_define_const(mCreateTransferResult, "TIMEOUT_RESERVED_FOR_PENDING_TRANSFER", INT2NUM(17));
  rb_define_const(mCreateTransferResult, "CLOSING_TRANSFER_MUST_BE_PENDING", INT2NUM(64));
  rb_define_const(mCreateTransferResult, "LEDGER_MUST_NOT_BE_ZERO", INT2NUM(19));
  rb_define_const(mCreateTransferResult, "CODE_MUST_NOT_BE_ZERO", INT2NUM(20));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_NOT_FOUND", INT2NUM(21));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_NOT_FOUND", INT2NUM(22));
  rb_define_const(mCreateTransferResult, "ACCOUNTS_MUST_HAVE_THE_SAME_LEDGER", INT2NUM(23));
  rb_define_const(mCreateTransferResult, "TRANSFER_MUST_HAVE_THE_SAME_LEDGER_AS_ACCOUNTS", INT2NUM(24));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_NOT_FOUND", INT2NUM(25));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_NOT_PENDING", INT2NUM(26));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_DEBIT_ACCOUNT_ID", INT2NUM(27));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_CREDIT_ACCOUNT_ID", INT2NUM(28));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_LEDGER", INT2NUM(29));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_CODE", INT2NUM(30));
  rb_define_const(mCreateTransferResult, "EXCEEDS_PENDING_TRANSFER_AMOUNT", INT2NUM(31));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_AMOUNT", INT2NUM(32));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_ALREADY_POSTED", INT2NUM(33));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_ALREADY_VOIDED", INT2NUM(34));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_EXPIRED", INT2NUM(35));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS", INT2NUM(60));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_DEBIT_ACCOUNT", INT2NUM(61));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_CREDIT_ACCOUNT", INT2NUM(62));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMEOUT_MUST_BE_ZERO", INT2NUM(63));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ALREADY_CLOSED", INT2NUM(65));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ALREADY_CLOSED", INT2NUM(66));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS_PENDING", INT2NUM(47));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS_PENDING", INT2NUM(48));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS_POSTED", INT2NUM(49));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS_POSTED", INT2NUM(50));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS", INT2NUM(51));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS", INT2NUM(52));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_TIMEOUT", INT2NUM(53));
  rb_define_const(mCreateTransferResult, "EXCEEDS_CREDITS", INT2NUM(54));
  rb_define_const(mCreateTransferResult, "EXCEEDS_DEBITS", INT2NUM(55));

  VALUE rb_cData = rb_const_get(rb_cObject, rb_intern("Data"));

  VALUE tb_packet_t_args[7];
  tb_packet_t_args[0] = ID2SYM(rb_intern("user_data"));
  tb_packet_t_args[1] = ID2SYM(rb_intern("data"));
  tb_packet_t_args[2] = ID2SYM(rb_intern("data_size"));
  tb_packet_t_args[3] = ID2SYM(rb_intern("user_tag"));
  tb_packet_t_args[4] = ID2SYM(rb_intern("operation"));
  tb_packet_t_args[5] = ID2SYM(rb_intern("status"));
  tb_packet_t_args[6] = ID2SYM(rb_intern("opaque"));

  VALUE tb_packet_t_class = rb_funcallv(rb_cData, rb_intern("define"), 7, tb_packet_t_args);
  rb_define_const(mTigerBeetleBindings, "Packet", tb_packet_t_class);

  VALUE tb_client_t_args[1];
  tb_client_t_args[0] = ID2SYM(rb_intern("opaque"));

  VALUE tb_client_t_class = rb_funcallv(rb_cData, rb_intern("define"), 1, tb_client_t_args);
  rb_define_const(mTigerBeetleBindings, "Client", tb_client_t_class);

  VALUE tb_account_t_args[13];
  tb_account_t_args[0] = ID2SYM(rb_intern("id"));
  tb_account_t_args[1] = ID2SYM(rb_intern("debits_pending"));
  tb_account_t_args[2] = ID2SYM(rb_intern("debits_posted"));
  tb_account_t_args[3] = ID2SYM(rb_intern("credits_pending"));
  tb_account_t_args[4] = ID2SYM(rb_intern("credits_posted"));
  tb_account_t_args[5] = ID2SYM(rb_intern("user_data_128"));
  tb_account_t_args[6] = ID2SYM(rb_intern("user_data_64"));
  tb_account_t_args[7] = ID2SYM(rb_intern("user_data_32"));
  tb_account_t_args[8] = ID2SYM(rb_intern("reserved"));
  tb_account_t_args[9] = ID2SYM(rb_intern("ledger"));
  tb_account_t_args[10] = ID2SYM(rb_intern("code"));
  tb_account_t_args[11] = ID2SYM(rb_intern("flags"));
  tb_account_t_args[12] = ID2SYM(rb_intern("timestamp"));

  VALUE tb_account_t_class = rb_funcallv(rb_cData, rb_intern("define"), 13, tb_account_t_args);
  rb_define_const(mTigerBeetleBindings, "Account", tb_account_t_class);

  VALUE tb_transfer_t_args[13];
  tb_transfer_t_args[0] = ID2SYM(rb_intern("id"));
  tb_transfer_t_args[1] = ID2SYM(rb_intern("debit_account_id"));
  tb_transfer_t_args[2] = ID2SYM(rb_intern("credit_account_id"));
  tb_transfer_t_args[3] = ID2SYM(rb_intern("amount"));
  tb_transfer_t_args[4] = ID2SYM(rb_intern("pending_id"));
  tb_transfer_t_args[5] = ID2SYM(rb_intern("user_data_128"));
  tb_transfer_t_args[6] = ID2SYM(rb_intern("user_data_64"));
  tb_transfer_t_args[7] = ID2SYM(rb_intern("user_data_32"));
  tb_transfer_t_args[8] = ID2SYM(rb_intern("timeout"));
  tb_transfer_t_args[9] = ID2SYM(rb_intern("ledger"));
  tb_transfer_t_args[10] = ID2SYM(rb_intern("code"));
  tb_transfer_t_args[11] = ID2SYM(rb_intern("flags"));
  tb_transfer_t_args[12] = ID2SYM(rb_intern("timestamp"));

  VALUE tb_transfer_t_class = rb_funcallv(rb_cData, rb_intern("define"), 13, tb_transfer_t_args);
  rb_define_const(mTigerBeetleBindings, "Transfer", tb_transfer_t_class);

  VALUE tb_account_filter_t_args[10];
  tb_account_filter_t_args[0] = ID2SYM(rb_intern("account_id"));
  tb_account_filter_t_args[1] = ID2SYM(rb_intern("user_data_128"));
  tb_account_filter_t_args[2] = ID2SYM(rb_intern("user_data_64"));
  tb_account_filter_t_args[3] = ID2SYM(rb_intern("user_data_32"));
  tb_account_filter_t_args[4] = ID2SYM(rb_intern("code"));
  tb_account_filter_t_args[5] = ID2SYM(rb_intern("reserved"));
  tb_account_filter_t_args[6] = ID2SYM(rb_intern("timestamp_min"));
  tb_account_filter_t_args[7] = ID2SYM(rb_intern("timestamp_max"));
  tb_account_filter_t_args[8] = ID2SYM(rb_intern("limit"));
  tb_account_filter_t_args[9] = ID2SYM(rb_intern("flags"));

  VALUE tb_account_filter_t_class = rb_funcallv(rb_cData, rb_intern("define"), 10, tb_account_filter_t_args);
  rb_define_const(mTigerBeetleBindings, "AccountFilter", tb_account_filter_t_class);

  VALUE tb_account_balance_t_args[6];
  tb_account_balance_t_args[0] = ID2SYM(rb_intern("debits_pending"));
  tb_account_balance_t_args[1] = ID2SYM(rb_intern("debits_posted"));
  tb_account_balance_t_args[2] = ID2SYM(rb_intern("credits_pending"));
  tb_account_balance_t_args[3] = ID2SYM(rb_intern("credits_posted"));
  tb_account_balance_t_args[4] = ID2SYM(rb_intern("timestamp"));
  tb_account_balance_t_args[5] = ID2SYM(rb_intern("reserved"));

  VALUE tb_account_balance_t_class = rb_funcallv(rb_cData, rb_intern("define"), 6, tb_account_balance_t_args);
  rb_define_const(mTigerBeetleBindings, "AccountBalance", tb_account_balance_t_class);

  VALUE tb_query_filter_t_args[10];
  tb_query_filter_t_args[0] = ID2SYM(rb_intern("user_data_128"));
  tb_query_filter_t_args[1] = ID2SYM(rb_intern("user_data_64"));
  tb_query_filter_t_args[2] = ID2SYM(rb_intern("user_data_32"));
  tb_query_filter_t_args[3] = ID2SYM(rb_intern("ledger"));
  tb_query_filter_t_args[4] = ID2SYM(rb_intern("code"));
  tb_query_filter_t_args[5] = ID2SYM(rb_intern("reserved"));
  tb_query_filter_t_args[6] = ID2SYM(rb_intern("timestamp_min"));
  tb_query_filter_t_args[7] = ID2SYM(rb_intern("timestamp_max"));
  tb_query_filter_t_args[8] = ID2SYM(rb_intern("limit"));
  tb_query_filter_t_args[9] = ID2SYM(rb_intern("flags"));

  VALUE tb_query_filter_t_class = rb_funcallv(rb_cData, rb_intern("define"), 10, tb_query_filter_t_args);
  rb_define_const(mTigerBeetleBindings, "QueryFilter", tb_query_filter_t_class);

}
