//////////////////////////////////////////////////////////////
// This file was auto-generated by ruby_native_bindings.zig //
//              Do not manually modify.                     //
//////////////////////////////////////////////////////////////

#include <ruby.h>
#include "tb_client.h"
#include "tb_macros.h"

void tb_define_enums_and_bitmasks(VALUE module) {

  VALUE mOperation = rb_define_module_under(module, "Operation");
  rb_define_const(mOperation, "PULSE", INT2NUM(128));
  rb_define_const(mOperation, "GET_EVENTS", INT2NUM(137));
  rb_define_const(mOperation, "CREATE_ACCOUNTS", INT2NUM(138));
  rb_define_const(mOperation, "CREATE_TRANSFERS", INT2NUM(139));
  rb_define_const(mOperation, "LOOKUP_ACCOUNTS", INT2NUM(140));
  rb_define_const(mOperation, "LOOKUP_TRANSFERS", INT2NUM(141));
  rb_define_const(mOperation, "GET_ACCOUNT_TRANSFERS", INT2NUM(142));
  rb_define_const(mOperation, "GET_ACCOUNT_BALANCES", INT2NUM(143));
  rb_define_const(mOperation, "QUERY_ACCOUNTS", INT2NUM(144));
  rb_define_const(mOperation, "QUERY_TRANSFERS", INT2NUM(145));

  VALUE mPacketStatus = rb_define_module_under(module, "PacketStatus");
  rb_define_const(mPacketStatus, "OK", INT2NUM(0));
  rb_define_const(mPacketStatus, "TOO_MUCH_DATA", INT2NUM(1));
  rb_define_const(mPacketStatus, "CLIENT_EVICTED", INT2NUM(2));
  rb_define_const(mPacketStatus, "CLIENT_RELEASE_TOO_LOW", INT2NUM(3));
  rb_define_const(mPacketStatus, "CLIENT_RELEASE_TOO_HIGH", INT2NUM(4));
  rb_define_const(mPacketStatus, "CLIENT_SHUTDOWN", INT2NUM(5));
  rb_define_const(mPacketStatus, "INVALID_OPERATION", INT2NUM(6));
  rb_define_const(mPacketStatus, "INVALID_DATA_SIZE", INT2NUM(7));

  VALUE mInitStatus = rb_define_module_under(module, "InitStatus");
  rb_define_const(mInitStatus, "SUCCESS", INT2NUM(0));
  rb_define_const(mInitStatus, "UNEXPECTED", INT2NUM(1));
  rb_define_const(mInitStatus, "OUT_OF_MEMORY", INT2NUM(2));
  rb_define_const(mInitStatus, "ADDRESS_INVALID", INT2NUM(3));
  rb_define_const(mInitStatus, "ADDRESS_LIMIT_EXCEEDED", INT2NUM(4));
  rb_define_const(mInitStatus, "SYSTEM_RESOURCES", INT2NUM(5));
  rb_define_const(mInitStatus, "NETWORK_SUBSYSTEM", INT2NUM(6));

  VALUE mClientStatus = rb_define_module_under(module, "ClientStatus");
  rb_define_const(mClientStatus, "OK", INT2NUM(0));
  rb_define_const(mClientStatus, "INVALID", INT2NUM(1));

  VALUE mLogLevel = rb_define_module_under(module, "LogLevel");
  rb_define_const(mLogLevel, "ERR", INT2NUM(0));
  rb_define_const(mLogLevel, "WARN", INT2NUM(1));
  rb_define_const(mLogLevel, "INFO", INT2NUM(2));
  rb_define_const(mLogLevel, "DEBUG", INT2NUM(3));

  VALUE mRegisterLogCallbackStatus = rb_define_module_under(module, "RegisterLogCallbackStatus");
  rb_define_const(mRegisterLogCallbackStatus, "SUCCESS", INT2NUM(0));
  rb_define_const(mRegisterLogCallbackStatus, "ALREADY_REGISTERED", INT2NUM(1));
  rb_define_const(mRegisterLogCallbackStatus, "NOT_REGISTERED", INT2NUM(2));

  VALUE mAccountFlags = rb_define_module_under(module, "AccountFlags");
  rb_define_const(mAccountFlags, "LINKED", INT2NUM(1 << 0));
  rb_define_const(mAccountFlags, "DEBITS_MUST_NOT_EXCEED_CREDITS", INT2NUM(1 << 1));
  rb_define_const(mAccountFlags, "CREDITS_MUST_NOT_EXCEED_DEBITS", INT2NUM(1 << 2));
  rb_define_const(mAccountFlags, "HISTORY", INT2NUM(1 << 3));
  rb_define_const(mAccountFlags, "IMPORTED", INT2NUM(1 << 4));
  rb_define_const(mAccountFlags, "CLOSED", INT2NUM(1 << 5));

  VALUE mTransferFlags = rb_define_module_under(module, "TransferFlags");
  rb_define_const(mTransferFlags, "LINKED", INT2NUM(1 << 0));
  rb_define_const(mTransferFlags, "PENDING", INT2NUM(1 << 1));
  rb_define_const(mTransferFlags, "POST_PENDING_TRANSFER", INT2NUM(1 << 2));
  rb_define_const(mTransferFlags, "VOID_PENDING_TRANSFER", INT2NUM(1 << 3));
  rb_define_const(mTransferFlags, "BALANCING_DEBIT", INT2NUM(1 << 4));
  rb_define_const(mTransferFlags, "BALANCING_CREDIT", INT2NUM(1 << 5));
  rb_define_const(mTransferFlags, "CLOSING_DEBIT", INT2NUM(1 << 6));
  rb_define_const(mTransferFlags, "CLOSING_CREDIT", INT2NUM(1 << 7));
  rb_define_const(mTransferFlags, "IMPORTED", INT2NUM(1 << 8));

  VALUE mAccountFilterFlags = rb_define_module_under(module, "AccountFilterFlags");
  rb_define_const(mAccountFilterFlags, "DEBITS", INT2NUM(1 << 0));
  rb_define_const(mAccountFilterFlags, "CREDITS", INT2NUM(1 << 1));
  rb_define_const(mAccountFilterFlags, "REVERSED", INT2NUM(1 << 2));

  VALUE mQueryFilterFlags = rb_define_module_under(module, "QueryFilterFlags");
  rb_define_const(mQueryFilterFlags, "REVERSED", INT2NUM(1 << 0));

  VALUE mCreateAccountResult = rb_define_module_under(module, "CreateAccountResult");
  rb_define_const(mCreateAccountResult, "OK", INT2NUM(0));
  rb_define_const(mCreateAccountResult, "LINKED_EVENT_FAILED", INT2NUM(1));
  rb_define_const(mCreateAccountResult, "LINKED_EVENT_CHAIN_OPEN", INT2NUM(2));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_EXPECTED", INT2NUM(22));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_NOT_EXPECTED", INT2NUM(23));
  rb_define_const(mCreateAccountResult, "TIMESTAMP_MUST_BE_ZERO", INT2NUM(3));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE", INT2NUM(24));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE", INT2NUM(25));
  rb_define_const(mCreateAccountResult, "RESERVED_FIELD", INT2NUM(4));
  rb_define_const(mCreateAccountResult, "RESERVED_FLAG", INT2NUM(5));
  rb_define_const(mCreateAccountResult, "ID_MUST_NOT_BE_ZERO", INT2NUM(6));
  rb_define_const(mCreateAccountResult, "ID_MUST_NOT_BE_INT_MAX", INT2NUM(7));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_FLAGS", INT2NUM(15));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_128", INT2NUM(16));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_64", INT2NUM(17));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_32", INT2NUM(18));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_LEDGER", INT2NUM(19));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_CODE", INT2NUM(20));
  rb_define_const(mCreateAccountResult, "EXISTS", INT2NUM(21));
  rb_define_const(mCreateAccountResult, "FLAGS_ARE_MUTUALLY_EXCLUSIVE", INT2NUM(8));
  rb_define_const(mCreateAccountResult, "DEBITS_PENDING_MUST_BE_ZERO", INT2NUM(9));
  rb_define_const(mCreateAccountResult, "DEBITS_POSTED_MUST_BE_ZERO", INT2NUM(10));
  rb_define_const(mCreateAccountResult, "CREDITS_PENDING_MUST_BE_ZERO", INT2NUM(11));
  rb_define_const(mCreateAccountResult, "CREDITS_POSTED_MUST_BE_ZERO", INT2NUM(12));
  rb_define_const(mCreateAccountResult, "LEDGER_MUST_NOT_BE_ZERO", INT2NUM(13));
  rb_define_const(mCreateAccountResult, "CODE_MUST_NOT_BE_ZERO", INT2NUM(14));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS", INT2NUM(26));

  VALUE mCreateTransferResult = rb_define_module_under(module, "CreateTransferResult");
  rb_define_const(mCreateTransferResult, "OK", INT2NUM(0));
  rb_define_const(mCreateTransferResult, "LINKED_EVENT_FAILED", INT2NUM(1));
  rb_define_const(mCreateTransferResult, "LINKED_EVENT_CHAIN_OPEN", INT2NUM(2));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_EXPECTED", INT2NUM(56));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_NOT_EXPECTED", INT2NUM(57));
  rb_define_const(mCreateTransferResult, "TIMESTAMP_MUST_BE_ZERO", INT2NUM(3));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE", INT2NUM(58));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE", INT2NUM(59));
  rb_define_const(mCreateTransferResult, "RESERVED_FLAG", INT2NUM(4));
  rb_define_const(mCreateTransferResult, "ID_MUST_NOT_BE_ZERO", INT2NUM(5));
  rb_define_const(mCreateTransferResult, "ID_MUST_NOT_BE_INT_MAX", INT2NUM(6));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_FLAGS", INT2NUM(36));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_PENDING_ID", INT2NUM(40));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_TIMEOUT", INT2NUM(44));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_DEBIT_ACCOUNT_ID", INT2NUM(37));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_CREDIT_ACCOUNT_ID", INT2NUM(38));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_AMOUNT", INT2NUM(39));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_128", INT2NUM(41));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_64", INT2NUM(42));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_32", INT2NUM(43));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_LEDGER", INT2NUM(67));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_CODE", INT2NUM(45));
  rb_define_const(mCreateTransferResult, "EXISTS", INT2NUM(46));
  rb_define_const(mCreateTransferResult, "ID_ALREADY_FAILED", INT2NUM(68));
  rb_define_const(mCreateTransferResult, "FLAGS_ARE_MUTUALLY_EXCLUSIVE", INT2NUM(7));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ID_MUST_NOT_BE_ZERO", INT2NUM(8));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX", INT2NUM(9));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ID_MUST_NOT_BE_ZERO", INT2NUM(10));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX", INT2NUM(11));
  rb_define_const(mCreateTransferResult, "ACCOUNTS_MUST_BE_DIFFERENT", INT2NUM(12));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_BE_ZERO", INT2NUM(13));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_NOT_BE_ZERO", INT2NUM(14));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_NOT_BE_INT_MAX", INT2NUM(15));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_BE_DIFFERENT", INT2NUM(16));
  rb_define_const(mCreateTransferResult, "TIMEOUT_RESERVED_FOR_PENDING_TRANSFER", INT2NUM(17));
  rb_define_const(mCreateTransferResult, "CLOSING_TRANSFER_MUST_BE_PENDING", INT2NUM(64));
  rb_define_const(mCreateTransferResult, "LEDGER_MUST_NOT_BE_ZERO", INT2NUM(19));
  rb_define_const(mCreateTransferResult, "CODE_MUST_NOT_BE_ZERO", INT2NUM(20));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_NOT_FOUND", INT2NUM(21));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_NOT_FOUND", INT2NUM(22));
  rb_define_const(mCreateTransferResult, "ACCOUNTS_MUST_HAVE_THE_SAME_LEDGER", INT2NUM(23));
  rb_define_const(mCreateTransferResult, "TRANSFER_MUST_HAVE_THE_SAME_LEDGER_AS_ACCOUNTS", INT2NUM(24));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_NOT_FOUND", INT2NUM(25));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_NOT_PENDING", INT2NUM(26));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_DEBIT_ACCOUNT_ID", INT2NUM(27));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_CREDIT_ACCOUNT_ID", INT2NUM(28));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_LEDGER", INT2NUM(29));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_CODE", INT2NUM(30));
  rb_define_const(mCreateTransferResult, "EXCEEDS_PENDING_TRANSFER_AMOUNT", INT2NUM(31));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_AMOUNT", INT2NUM(32));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_ALREADY_POSTED", INT2NUM(33));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_ALREADY_VOIDED", INT2NUM(34));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_EXPIRED", INT2NUM(35));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS", INT2NUM(60));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_DEBIT_ACCOUNT", INT2NUM(61));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_CREDIT_ACCOUNT", INT2NUM(62));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMEOUT_MUST_BE_ZERO", INT2NUM(63));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ALREADY_CLOSED", INT2NUM(65));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ALREADY_CLOSED", INT2NUM(66));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS_PENDING", INT2NUM(47));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS_PENDING", INT2NUM(48));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS_POSTED", INT2NUM(49));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS_POSTED", INT2NUM(50));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS", INT2NUM(51));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS", INT2NUM(52));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_TIMEOUT", INT2NUM(53));
  rb_define_const(mCreateTransferResult, "EXCEEDS_CREDITS", INT2NUM(54));
  rb_define_const(mCreateTransferResult, "EXCEEDS_DEBITS", INT2NUM(55));

}

// Packet - tb_packet
DEFINE_RB_CLASS_FOR_STRUCT(tb_packet)
DEFINE_VOID_PTR_ACCESSORS(tb_packet, user_data)
DEFINE_VOID_PTR_ACCESSORS(tb_packet, data)
DEFINE_UINT_ACCESSORS(tb_packet, uint32_t, data_size)
DEFINE_UINT_ACCESSORS(tb_packet, uint16_t, user_tag)
DEFINE_UINT_ACCESSORS(tb_packet, uint8_t, operation)
DEFINE_UINT_ACCESSORS(tb_packet, uint8_t, status)


// Client - tb_client
DEFINE_RB_CLASS_FOR_STRUCT(tb_client)


// Account - tb_account
DEFINE_RB_CLASS_FOR_STRUCT(tb_account)
DEFINE_UINT128_ACCESSORS(tb_account, id)
DEFINE_UINT128_ACCESSORS(tb_account, debits_pending)
DEFINE_UINT128_ACCESSORS(tb_account, debits_posted)
DEFINE_UINT128_ACCESSORS(tb_account, credits_pending)
DEFINE_UINT128_ACCESSORS(tb_account, credits_posted)
DEFINE_UINT128_ACCESSORS(tb_account, user_data_128)
DEFINE_UINT_ACCESSORS(tb_account, uint64_t, user_data_64)
DEFINE_UINT_ACCESSORS(tb_account, uint32_t, user_data_32)
DEFINE_UINT_ACCESSORS(tb_account, uint32_t, ledger)
DEFINE_UINT_ACCESSORS(tb_account, uint16_t, code)
DEFINE_UINT_ACCESSORS(tb_account, uint16_t, flags)
DEFINE_UINT_ACCESSORS(tb_account, uint64_t, timestamp)


// Transfer - tb_transfer
DEFINE_RB_CLASS_FOR_STRUCT(tb_transfer)
DEFINE_UINT128_ACCESSORS(tb_transfer, id)
DEFINE_UINT128_ACCESSORS(tb_transfer, debit_account_id)
DEFINE_UINT128_ACCESSORS(tb_transfer, credit_account_id)
DEFINE_UINT128_ACCESSORS(tb_transfer, amount)
DEFINE_UINT128_ACCESSORS(tb_transfer, pending_id)
DEFINE_UINT128_ACCESSORS(tb_transfer, user_data_128)
DEFINE_UINT_ACCESSORS(tb_transfer, uint64_t, user_data_64)
DEFINE_UINT_ACCESSORS(tb_transfer, uint32_t, user_data_32)
DEFINE_UINT_ACCESSORS(tb_transfer, uint32_t, timeout)
DEFINE_UINT_ACCESSORS(tb_transfer, uint32_t, ledger)
DEFINE_UINT_ACCESSORS(tb_transfer, uint16_t, code)
DEFINE_UINT_ACCESSORS(tb_transfer, uint16_t, flags)
DEFINE_UINT_ACCESSORS(tb_transfer, uint64_t, timestamp)


// AccountFilter - tb_account_filter
DEFINE_RB_CLASS_FOR_STRUCT(tb_account_filter)
DEFINE_UINT128_ACCESSORS(tb_account_filter, account_id)
DEFINE_UINT128_ACCESSORS(tb_account_filter, user_data_128)
DEFINE_UINT_ACCESSORS(tb_account_filter, uint64_t, user_data_64)
DEFINE_UINT_ACCESSORS(tb_account_filter, uint32_t, user_data_32)
DEFINE_UINT_ACCESSORS(tb_account_filter, uint16_t, code)
DEFINE_UINT_ACCESSORS(tb_account_filter, uint64_t, timestamp_min)
DEFINE_UINT_ACCESSORS(tb_account_filter, uint64_t, timestamp_max)
DEFINE_UINT_ACCESSORS(tb_account_filter, uint32_t, limit)
DEFINE_UINT_ACCESSORS(tb_account_filter, uint32_t, flags)


// AccountBalance - tb_account_balance
DEFINE_RB_CLASS_FOR_STRUCT(tb_account_balance)
DEFINE_UINT128_ACCESSORS(tb_account_balance, debits_pending)
DEFINE_UINT128_ACCESSORS(tb_account_balance, debits_posted)
DEFINE_UINT128_ACCESSORS(tb_account_balance, credits_pending)
DEFINE_UINT128_ACCESSORS(tb_account_balance, credits_posted)
DEFINE_UINT_ACCESSORS(tb_account_balance, uint64_t, timestamp)


// QueryFilter - tb_query_filter
DEFINE_RB_CLASS_FOR_STRUCT(tb_query_filter)
DEFINE_UINT128_ACCESSORS(tb_query_filter, user_data_128)
DEFINE_UINT_ACCESSORS(tb_query_filter, uint64_t, user_data_64)
DEFINE_UINT_ACCESSORS(tb_query_filter, uint32_t, user_data_32)
DEFINE_UINT_ACCESSORS(tb_query_filter, uint32_t, ledger)
DEFINE_UINT_ACCESSORS(tb_query_filter, uint16_t, code)
DEFINE_UINT_ACCESSORS(tb_query_filter, uint64_t, timestamp_min)
DEFINE_UINT_ACCESSORS(tb_query_filter, uint64_t, timestamp_max)
DEFINE_UINT_ACCESSORS(tb_query_filter, uint32_t, limit)
DEFINE_UINT_ACCESSORS(tb_query_filter, uint32_t, flags)


//Ruby method accessors
void tb_define_ruby_accessors(VALUE module) {

  VALUE m_Packet_klass = rb_define_class_under(module, "Packet", rb_cObject);
  rb_define_alloc_func(m_Packet_klass, rb_tb_packet_alloc);
  rb_define_method(m_Packet_klass, "initialize", rb_tb_packet_initialize, -1);
  DEFINE_ACCESSORS_METHODS(tb_packet, user_data, m_Packet_klass)
  DEFINE_ACCESSORS_METHODS(tb_packet, data, m_Packet_klass)
  DEFINE_ACCESSORS_METHODS(tb_packet, data_size, m_Packet_klass)
  DEFINE_ACCESSORS_METHODS(tb_packet, user_tag, m_Packet_klass)
  DEFINE_ACCESSORS_METHODS(tb_packet, operation, m_Packet_klass)
  DEFINE_ACCESSORS_METHODS(tb_packet, status, m_Packet_klass)

  VALUE m_Client_klass = rb_define_class_under(module, "Client", rb_cObject);
  rb_define_alloc_func(m_Client_klass, rb_tb_client_alloc);
  rb_define_method(m_Client_klass, "initialize", rb_tb_client_initialize, -1);

  VALUE m_Account_klass = rb_define_class_under(module, "Account", rb_cObject);
  rb_define_alloc_func(m_Account_klass, rb_tb_account_alloc);
  rb_define_method(m_Account_klass, "initialize", rb_tb_account_initialize, -1);
  DEFINE_ACCESSORS_METHODS(tb_account, id, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, debits_pending, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, debits_posted, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, credits_pending, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, credits_posted, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, user_data_128, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, user_data_64, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, user_data_32, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, ledger, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, code, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, flags, m_Account_klass)
  DEFINE_ACCESSORS_METHODS(tb_account, timestamp, m_Account_klass)

  VALUE m_Transfer_klass = rb_define_class_under(module, "Transfer", rb_cObject);
  rb_define_alloc_func(m_Transfer_klass, rb_tb_transfer_alloc);
  rb_define_method(m_Transfer_klass, "initialize", rb_tb_transfer_initialize, -1);
  DEFINE_ACCESSORS_METHODS(tb_transfer, id, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, debit_account_id, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, credit_account_id, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, amount, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, pending_id, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, user_data_128, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, user_data_64, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, user_data_32, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, timeout, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, ledger, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, code, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, flags, m_Transfer_klass)
  DEFINE_ACCESSORS_METHODS(tb_transfer, timestamp, m_Transfer_klass)

  VALUE m_AccountFilter_klass = rb_define_class_under(module, "AccountFilter", rb_cObject);
  rb_define_alloc_func(m_AccountFilter_klass, rb_tb_account_filter_alloc);
  rb_define_method(m_AccountFilter_klass, "initialize", rb_tb_account_filter_initialize, -1);
  DEFINE_ACCESSORS_METHODS(tb_account_filter, account_id, m_AccountFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_filter, user_data_128, m_AccountFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_filter, user_data_64, m_AccountFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_filter, user_data_32, m_AccountFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_filter, code, m_AccountFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_filter, timestamp_min, m_AccountFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_filter, timestamp_max, m_AccountFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_filter, limit, m_AccountFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_filter, flags, m_AccountFilter_klass)

  VALUE m_AccountBalance_klass = rb_define_class_under(module, "AccountBalance", rb_cObject);
  rb_define_alloc_func(m_AccountBalance_klass, rb_tb_account_balance_alloc);
  rb_define_method(m_AccountBalance_klass, "initialize", rb_tb_account_balance_initialize, -1);
  DEFINE_ACCESSORS_METHODS(tb_account_balance, debits_pending, m_AccountBalance_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_balance, debits_posted, m_AccountBalance_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_balance, credits_pending, m_AccountBalance_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_balance, credits_posted, m_AccountBalance_klass)
  DEFINE_ACCESSORS_METHODS(tb_account_balance, timestamp, m_AccountBalance_klass)

  VALUE m_QueryFilter_klass = rb_define_class_under(module, "QueryFilter", rb_cObject);
  rb_define_alloc_func(m_QueryFilter_klass, rb_tb_query_filter_alloc);
  rb_define_method(m_QueryFilter_klass, "initialize", rb_tb_query_filter_initialize, -1);
  DEFINE_ACCESSORS_METHODS(tb_query_filter, user_data_128, m_QueryFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_query_filter, user_data_64, m_QueryFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_query_filter, user_data_32, m_QueryFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_query_filter, ledger, m_QueryFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_query_filter, code, m_QueryFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_query_filter, timestamp_min, m_QueryFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_query_filter, timestamp_max, m_QueryFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_query_filter, limit, m_QueryFilter_klass)
  DEFINE_ACCESSORS_METHODS(tb_query_filter, flags, m_QueryFilter_klass)
}
