/*##############################################################*/
/*## This file was auto-generated by ruby_native_bindings.zig ##*/
/*##              Do not manually modify.                     ##*/
/*##############################################################*/

#include <ruby.h>
#include "tb_client.h"
#include "tigerbeetle/shared.c"

void Init_tigerbeetle() {
  VALUE mTigerBeetle = rb_define_module("TigerBeetle");
  VALUE mTigerBeetleBindings = rb_define_module_under(mTigerBeetle, "Bindings");

  VALUE mOperation = rb_define_module_under(mTigerBeetleBindings, "Operation");
  rb_define_const(mOperation, "PULSE", INT2NUM(128));
  rb_define_const(mOperation, "GET_EVENTS", INT2NUM(137));
  rb_define_const(mOperation, "CREATE_ACCOUNTS", INT2NUM(138));
  rb_define_const(mOperation, "CREATE_TRANSFERS", INT2NUM(139));
  rb_define_const(mOperation, "LOOKUP_ACCOUNTS", INT2NUM(140));
  rb_define_const(mOperation, "LOOKUP_TRANSFERS", INT2NUM(141));
  rb_define_const(mOperation, "GET_ACCOUNT_TRANSFERS", INT2NUM(142));
  rb_define_const(mOperation, "GET_ACCOUNT_BALANCES", INT2NUM(143));
  rb_define_const(mOperation, "QUERY_ACCOUNTS", INT2NUM(144));
  rb_define_const(mOperation, "QUERY_TRANSFERS", INT2NUM(145));

  VALUE mPacketStatus = rb_define_module_under(mTigerBeetleBindings, "PacketStatus");
  rb_define_const(mPacketStatus, "OK", INT2NUM(0));
  rb_define_const(mPacketStatus, "TOO_MUCH_DATA", INT2NUM(1));
  rb_define_const(mPacketStatus, "CLIENT_EVICTED", INT2NUM(2));
  rb_define_const(mPacketStatus, "CLIENT_RELEASE_TOO_LOW", INT2NUM(3));
  rb_define_const(mPacketStatus, "CLIENT_RELEASE_TOO_HIGH", INT2NUM(4));
  rb_define_const(mPacketStatus, "CLIENT_SHUTDOWN", INT2NUM(5));
  rb_define_const(mPacketStatus, "INVALID_OPERATION", INT2NUM(6));
  rb_define_const(mPacketStatus, "INVALID_DATA_SIZE", INT2NUM(7));

  VALUE mInitStatus = rb_define_module_under(mTigerBeetleBindings, "InitStatus");
  rb_define_const(mInitStatus, "SUCCESS", INT2NUM(0));
  rb_define_const(mInitStatus, "UNEXPECTED", INT2NUM(1));
  rb_define_const(mInitStatus, "OUT_OF_MEMORY", INT2NUM(2));
  rb_define_const(mInitStatus, "ADDRESS_INVALID", INT2NUM(3));
  rb_define_const(mInitStatus, "ADDRESS_LIMIT_EXCEEDED", INT2NUM(4));
  rb_define_const(mInitStatus, "SYSTEM_RESOURCES", INT2NUM(5));
  rb_define_const(mInitStatus, "NETWORK_SUBSYSTEM", INT2NUM(6));

  VALUE mClientStatus = rb_define_module_under(mTigerBeetleBindings, "ClientStatus");
  rb_define_const(mClientStatus, "OK", INT2NUM(0));
  rb_define_const(mClientStatus, "INVALID", INT2NUM(1));

  VALUE mLogLevel = rb_define_module_under(mTigerBeetleBindings, "LogLevel");
  rb_define_const(mLogLevel, "ERR", INT2NUM(0));
  rb_define_const(mLogLevel, "WARN", INT2NUM(1));
  rb_define_const(mLogLevel, "INFO", INT2NUM(2));
  rb_define_const(mLogLevel, "DEBUG", INT2NUM(3));

  VALUE mRegisterLogCallbackStatus = rb_define_module_under(mTigerBeetleBindings, "RegisterLogCallbackStatus");
  rb_define_const(mRegisterLogCallbackStatus, "SUCCESS", INT2NUM(0));
  rb_define_const(mRegisterLogCallbackStatus, "ALREADY_REGISTERED", INT2NUM(1));
  rb_define_const(mRegisterLogCallbackStatus, "NOT_REGISTERED", INT2NUM(2));

  VALUE mAccountFlags = rb_define_module_under(mTigerBeetleBindings, "AccountFlags");
  rb_define_const(mAccountFlags, "LINKED", INT2NUM(1 << 0));
  rb_define_const(mAccountFlags, "DEBITS_MUST_NOT_EXCEED_CREDITS", INT2NUM(1 << 1));
  rb_define_const(mAccountFlags, "CREDITS_MUST_NOT_EXCEED_DEBITS", INT2NUM(1 << 2));
  rb_define_const(mAccountFlags, "HISTORY", INT2NUM(1 << 3));
  rb_define_const(mAccountFlags, "IMPORTED", INT2NUM(1 << 4));
  rb_define_const(mAccountFlags, "CLOSED", INT2NUM(1 << 5));

  VALUE mTransferFlags = rb_define_module_under(mTigerBeetleBindings, "TransferFlags");
  rb_define_const(mTransferFlags, "LINKED", INT2NUM(1 << 0));
  rb_define_const(mTransferFlags, "PENDING", INT2NUM(1 << 1));
  rb_define_const(mTransferFlags, "POST_PENDING_TRANSFER", INT2NUM(1 << 2));
  rb_define_const(mTransferFlags, "VOID_PENDING_TRANSFER", INT2NUM(1 << 3));
  rb_define_const(mTransferFlags, "BALANCING_DEBIT", INT2NUM(1 << 4));
  rb_define_const(mTransferFlags, "BALANCING_CREDIT", INT2NUM(1 << 5));
  rb_define_const(mTransferFlags, "CLOSING_DEBIT", INT2NUM(1 << 6));
  rb_define_const(mTransferFlags, "CLOSING_CREDIT", INT2NUM(1 << 7));
  rb_define_const(mTransferFlags, "IMPORTED", INT2NUM(1 << 8));

  VALUE mAccountFilterFlags = rb_define_module_under(mTigerBeetleBindings, "AccountFilterFlags");
  rb_define_const(mAccountFilterFlags, "DEBITS", INT2NUM(1 << 0));
  rb_define_const(mAccountFilterFlags, "CREDITS", INT2NUM(1 << 1));
  rb_define_const(mAccountFilterFlags, "REVERSED", INT2NUM(1 << 2));

  VALUE mQueryFilterFlags = rb_define_module_under(mTigerBeetleBindings, "QueryFilterFlags");
  rb_define_const(mQueryFilterFlags, "REVERSED", INT2NUM(1 << 0));

  VALUE mCreateAccountResult = rb_define_module_under(mTigerBeetleBindings, "CreateAccountResult");
  rb_define_const(mCreateAccountResult, "OK", INT2NUM(0));
  rb_define_const(mCreateAccountResult, "LINKED_EVENT_FAILED", INT2NUM(1));
  rb_define_const(mCreateAccountResult, "LINKED_EVENT_CHAIN_OPEN", INT2NUM(2));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_EXPECTED", INT2NUM(22));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_NOT_EXPECTED", INT2NUM(23));
  rb_define_const(mCreateAccountResult, "TIMESTAMP_MUST_BE_ZERO", INT2NUM(3));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE", INT2NUM(24));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE", INT2NUM(25));
  rb_define_const(mCreateAccountResult, "RESERVED_FIELD", INT2NUM(4));
  rb_define_const(mCreateAccountResult, "RESERVED_FLAG", INT2NUM(5));
  rb_define_const(mCreateAccountResult, "ID_MUST_NOT_BE_ZERO", INT2NUM(6));
  rb_define_const(mCreateAccountResult, "ID_MUST_NOT_BE_INT_MAX", INT2NUM(7));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_FLAGS", INT2NUM(15));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_128", INT2NUM(16));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_64", INT2NUM(17));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_USER_DATA_32", INT2NUM(18));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_LEDGER", INT2NUM(19));
  rb_define_const(mCreateAccountResult, "EXISTS_WITH_DIFFERENT_CODE", INT2NUM(20));
  rb_define_const(mCreateAccountResult, "EXISTS", INT2NUM(21));
  rb_define_const(mCreateAccountResult, "FLAGS_ARE_MUTUALLY_EXCLUSIVE", INT2NUM(8));
  rb_define_const(mCreateAccountResult, "DEBITS_PENDING_MUST_BE_ZERO", INT2NUM(9));
  rb_define_const(mCreateAccountResult, "DEBITS_POSTED_MUST_BE_ZERO", INT2NUM(10));
  rb_define_const(mCreateAccountResult, "CREDITS_PENDING_MUST_BE_ZERO", INT2NUM(11));
  rb_define_const(mCreateAccountResult, "CREDITS_POSTED_MUST_BE_ZERO", INT2NUM(12));
  rb_define_const(mCreateAccountResult, "LEDGER_MUST_NOT_BE_ZERO", INT2NUM(13));
  rb_define_const(mCreateAccountResult, "CODE_MUST_NOT_BE_ZERO", INT2NUM(14));
  rb_define_const(mCreateAccountResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS", INT2NUM(26));

  VALUE mCreateTransferResult = rb_define_module_under(mTigerBeetleBindings, "CreateTransferResult");
  rb_define_const(mCreateTransferResult, "OK", INT2NUM(0));
  rb_define_const(mCreateTransferResult, "LINKED_EVENT_FAILED", INT2NUM(1));
  rb_define_const(mCreateTransferResult, "LINKED_EVENT_CHAIN_OPEN", INT2NUM(2));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_EXPECTED", INT2NUM(56));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_NOT_EXPECTED", INT2NUM(57));
  rb_define_const(mCreateTransferResult, "TIMESTAMP_MUST_BE_ZERO", INT2NUM(3));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_OUT_OF_RANGE", INT2NUM(58));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_ADVANCE", INT2NUM(59));
  rb_define_const(mCreateTransferResult, "RESERVED_FLAG", INT2NUM(4));
  rb_define_const(mCreateTransferResult, "ID_MUST_NOT_BE_ZERO", INT2NUM(5));
  rb_define_const(mCreateTransferResult, "ID_MUST_NOT_BE_INT_MAX", INT2NUM(6));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_FLAGS", INT2NUM(36));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_PENDING_ID", INT2NUM(40));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_TIMEOUT", INT2NUM(44));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_DEBIT_ACCOUNT_ID", INT2NUM(37));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_CREDIT_ACCOUNT_ID", INT2NUM(38));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_AMOUNT", INT2NUM(39));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_128", INT2NUM(41));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_64", INT2NUM(42));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_USER_DATA_32", INT2NUM(43));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_LEDGER", INT2NUM(67));
  rb_define_const(mCreateTransferResult, "EXISTS_WITH_DIFFERENT_CODE", INT2NUM(45));
  rb_define_const(mCreateTransferResult, "EXISTS", INT2NUM(46));
  rb_define_const(mCreateTransferResult, "ID_ALREADY_FAILED", INT2NUM(68));
  rb_define_const(mCreateTransferResult, "FLAGS_ARE_MUTUALLY_EXCLUSIVE", INT2NUM(7));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ID_MUST_NOT_BE_ZERO", INT2NUM(8));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX", INT2NUM(9));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ID_MUST_NOT_BE_ZERO", INT2NUM(10));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ID_MUST_NOT_BE_INT_MAX", INT2NUM(11));
  rb_define_const(mCreateTransferResult, "ACCOUNTS_MUST_BE_DIFFERENT", INT2NUM(12));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_BE_ZERO", INT2NUM(13));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_NOT_BE_ZERO", INT2NUM(14));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_NOT_BE_INT_MAX", INT2NUM(15));
  rb_define_const(mCreateTransferResult, "PENDING_ID_MUST_BE_DIFFERENT", INT2NUM(16));
  rb_define_const(mCreateTransferResult, "TIMEOUT_RESERVED_FOR_PENDING_TRANSFER", INT2NUM(17));
  rb_define_const(mCreateTransferResult, "CLOSING_TRANSFER_MUST_BE_PENDING", INT2NUM(64));
  rb_define_const(mCreateTransferResult, "LEDGER_MUST_NOT_BE_ZERO", INT2NUM(19));
  rb_define_const(mCreateTransferResult, "CODE_MUST_NOT_BE_ZERO", INT2NUM(20));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_NOT_FOUND", INT2NUM(21));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_NOT_FOUND", INT2NUM(22));
  rb_define_const(mCreateTransferResult, "ACCOUNTS_MUST_HAVE_THE_SAME_LEDGER", INT2NUM(23));
  rb_define_const(mCreateTransferResult, "TRANSFER_MUST_HAVE_THE_SAME_LEDGER_AS_ACCOUNTS", INT2NUM(24));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_NOT_FOUND", INT2NUM(25));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_NOT_PENDING", INT2NUM(26));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_DEBIT_ACCOUNT_ID", INT2NUM(27));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_CREDIT_ACCOUNT_ID", INT2NUM(28));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_LEDGER", INT2NUM(29));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_CODE", INT2NUM(30));
  rb_define_const(mCreateTransferResult, "EXCEEDS_PENDING_TRANSFER_AMOUNT", INT2NUM(31));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_HAS_DIFFERENT_AMOUNT", INT2NUM(32));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_ALREADY_POSTED", INT2NUM(33));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_ALREADY_VOIDED", INT2NUM(34));
  rb_define_const(mCreateTransferResult, "PENDING_TRANSFER_EXPIRED", INT2NUM(35));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_NOT_REGRESS", INT2NUM(60));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_DEBIT_ACCOUNT", INT2NUM(61));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMESTAMP_MUST_POSTDATE_CREDIT_ACCOUNT", INT2NUM(62));
  rb_define_const(mCreateTransferResult, "IMPORTED_EVENT_TIMEOUT_MUST_BE_ZERO", INT2NUM(63));
  rb_define_const(mCreateTransferResult, "DEBIT_ACCOUNT_ALREADY_CLOSED", INT2NUM(65));
  rb_define_const(mCreateTransferResult, "CREDIT_ACCOUNT_ALREADY_CLOSED", INT2NUM(66));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS_PENDING", INT2NUM(47));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS_PENDING", INT2NUM(48));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS_POSTED", INT2NUM(49));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS_POSTED", INT2NUM(50));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_DEBITS", INT2NUM(51));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_CREDITS", INT2NUM(52));
  rb_define_const(mCreateTransferResult, "OVERFLOWS_TIMEOUT", INT2NUM(53));
  rb_define_const(mCreateTransferResult, "EXCEEDS_CREDITS", INT2NUM(54));
  rb_define_const(mCreateTransferResult, "EXCEEDS_DEBITS", INT2NUM(55));

  VALUE rb_cData = rb_const_get(rb_cObject, rb_intern("Data"));

  VALUE Packet_args[7];
  Packet_args[0] = ID2SYM(rb_intern("user_data"));
  Packet_args[1] = ID2SYM(rb_intern("data"));
  Packet_args[2] = ID2SYM(rb_intern("data_size"));
  Packet_args[3] = ID2SYM(rb_intern("user_tag"));
  Packet_args[4] = ID2SYM(rb_intern("operation"));
  Packet_args[5] = ID2SYM(rb_intern("status"));
  Packet_args[6] = ID2SYM(rb_intern("opaque"));

  VALUE Packet_class = rb_funcallv(rb_cData, rb_intern("define"), 7, Packet_args);
  rb_define_const(mTigerBeetleBindings, "Packet", Packet_class);

  VALUE Client_args[1];
  Client_args[0] = ID2SYM(rb_intern("opaque"));

  VALUE Client_class = rb_funcallv(rb_cData, rb_intern("define"), 1, Client_args);
  rb_define_const(mTigerBeetleBindings, "Client", Client_class);

  VALUE Account_args[13];
  Account_args[0] = ID2SYM(rb_intern("id"));
  Account_args[1] = ID2SYM(rb_intern("debits_pending"));
  Account_args[2] = ID2SYM(rb_intern("debits_posted"));
  Account_args[3] = ID2SYM(rb_intern("credits_pending"));
  Account_args[4] = ID2SYM(rb_intern("credits_posted"));
  Account_args[5] = ID2SYM(rb_intern("user_data_128"));
  Account_args[6] = ID2SYM(rb_intern("user_data_64"));
  Account_args[7] = ID2SYM(rb_intern("user_data_32"));
  Account_args[8] = ID2SYM(rb_intern("reserved"));
  Account_args[9] = ID2SYM(rb_intern("ledger"));
  Account_args[10] = ID2SYM(rb_intern("code"));
  Account_args[11] = ID2SYM(rb_intern("flags"));
  Account_args[12] = ID2SYM(rb_intern("timestamp"));

  VALUE Account_class = rb_funcallv(rb_cData, rb_intern("define"), 13, Account_args);
  rb_define_const(mTigerBeetleBindings, "Account", Account_class);

  VALUE Transfer_args[13];
  Transfer_args[0] = ID2SYM(rb_intern("id"));
  Transfer_args[1] = ID2SYM(rb_intern("debit_account_id"));
  Transfer_args[2] = ID2SYM(rb_intern("credit_account_id"));
  Transfer_args[3] = ID2SYM(rb_intern("amount"));
  Transfer_args[4] = ID2SYM(rb_intern("pending_id"));
  Transfer_args[5] = ID2SYM(rb_intern("user_data_128"));
  Transfer_args[6] = ID2SYM(rb_intern("user_data_64"));
  Transfer_args[7] = ID2SYM(rb_intern("user_data_32"));
  Transfer_args[8] = ID2SYM(rb_intern("timeout"));
  Transfer_args[9] = ID2SYM(rb_intern("ledger"));
  Transfer_args[10] = ID2SYM(rb_intern("code"));
  Transfer_args[11] = ID2SYM(rb_intern("flags"));
  Transfer_args[12] = ID2SYM(rb_intern("timestamp"));

  VALUE Transfer_class = rb_funcallv(rb_cData, rb_intern("define"), 13, Transfer_args);
  rb_define_const(mTigerBeetleBindings, "Transfer", Transfer_class);

  VALUE CreateAccountsResult_args[2];
  CreateAccountsResult_args[0] = ID2SYM(rb_intern("index"));
  CreateAccountsResult_args[1] = ID2SYM(rb_intern("result"));

  VALUE CreateAccountsResult_class = rb_funcallv(rb_cData, rb_intern("define"), 2, CreateAccountsResult_args);
  rb_define_const(mTigerBeetleBindings, "CreateAccountsResult", CreateAccountsResult_class);

  VALUE CreateTransfersResult_args[2];
  CreateTransfersResult_args[0] = ID2SYM(rb_intern("index"));
  CreateTransfersResult_args[1] = ID2SYM(rb_intern("result"));

  VALUE CreateTransfersResult_class = rb_funcallv(rb_cData, rb_intern("define"), 2, CreateTransfersResult_args);
  rb_define_const(mTigerBeetleBindings, "CreateTransfersResult", CreateTransfersResult_class);

  VALUE AccountFilter_args[10];
  AccountFilter_args[0] = ID2SYM(rb_intern("account_id"));
  AccountFilter_args[1] = ID2SYM(rb_intern("user_data_128"));
  AccountFilter_args[2] = ID2SYM(rb_intern("user_data_64"));
  AccountFilter_args[3] = ID2SYM(rb_intern("user_data_32"));
  AccountFilter_args[4] = ID2SYM(rb_intern("code"));
  AccountFilter_args[5] = ID2SYM(rb_intern("reserved"));
  AccountFilter_args[6] = ID2SYM(rb_intern("timestamp_min"));
  AccountFilter_args[7] = ID2SYM(rb_intern("timestamp_max"));
  AccountFilter_args[8] = ID2SYM(rb_intern("limit"));
  AccountFilter_args[9] = ID2SYM(rb_intern("flags"));

  VALUE AccountFilter_class = rb_funcallv(rb_cData, rb_intern("define"), 10, AccountFilter_args);
  rb_define_const(mTigerBeetleBindings, "AccountFilter", AccountFilter_class);

  VALUE AccountBalance_args[6];
  AccountBalance_args[0] = ID2SYM(rb_intern("debits_pending"));
  AccountBalance_args[1] = ID2SYM(rb_intern("debits_posted"));
  AccountBalance_args[2] = ID2SYM(rb_intern("credits_pending"));
  AccountBalance_args[3] = ID2SYM(rb_intern("credits_posted"));
  AccountBalance_args[4] = ID2SYM(rb_intern("timestamp"));
  AccountBalance_args[5] = ID2SYM(rb_intern("reserved"));

  VALUE AccountBalance_class = rb_funcallv(rb_cData, rb_intern("define"), 6, AccountBalance_args);
  rb_define_const(mTigerBeetleBindings, "AccountBalance", AccountBalance_class);

  VALUE QueryFilter_args[10];
  QueryFilter_args[0] = ID2SYM(rb_intern("user_data_128"));
  QueryFilter_args[1] = ID2SYM(rb_intern("user_data_64"));
  QueryFilter_args[2] = ID2SYM(rb_intern("user_data_32"));
  QueryFilter_args[3] = ID2SYM(rb_intern("ledger"));
  QueryFilter_args[4] = ID2SYM(rb_intern("code"));
  QueryFilter_args[5] = ID2SYM(rb_intern("reserved"));
  QueryFilter_args[6] = ID2SYM(rb_intern("timestamp_min"));
  QueryFilter_args[7] = ID2SYM(rb_intern("timestamp_max"));
  QueryFilter_args[8] = ID2SYM(rb_intern("limit"));
  QueryFilter_args[9] = ID2SYM(rb_intern("flags"));

  VALUE QueryFilter_class = rb_funcallv(rb_cData, rb_intern("define"), 10, QueryFilter_args);
  rb_define_const(mTigerBeetleBindings, "QueryFilter", QueryFilter_class);

}
